force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Worldpay_Token__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Token__c</fullName>
    <inlineHelpText>The tokenized credit card number associated with this donation</inlineHelpText>
    <label>Worldpay Token</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Worldpay_Token__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Token__c</fullName>
    <inlineHelpText>The tokenized credit card number associated with this payment</inlineHelpText>
    <label>Worldpay Token</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonationFormPaymentBatchTest.cls
@isTest
public class DonationFormPaymentBatchTest {
    static testMethod void batchTestMethod() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, false)[0];
        testOpp.Worldpay_Token__c = '1234123412341234';
        insert testOpp;
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
            testPayment.Status__c = 'Pending';
            testPayment.Scheduled_Post_Date__c = Date.today();
        insert testPayment;

        Test.setMock(HttpCalloutMock.class, new VantivUtilitiesMock());
        DonationFormPaymentBatch paymentBatch = new DonationFormPaymentBatch();

        Test.startTest();
            Database.executeBatch(paymentBatch,2);
        Test.stopTest();

        Payment__c updatedPayment = [SELECT Id, Status__c, Amount__c FROM Payment__c WHERE Id = :testPayment.Id];
        System.assertEquals(PaymentServices.APPROVED_STATUS, updatedPayment.Status__c, 'Expect payment to be processed and approved');
    }

    static testMethod void testDatabaseFailure() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
            testPayment.Status__c = 'Pending';
            testPayment.Scheduled_Post_date__c = Date.today();
        insert testPayment;

        Test.setMock(HttpCalloutMock.class, new VantivUtilitiesMock());
        DonationFormPaymentBatch paymentBatch = new DonationFormPaymentBatch();
        paymentBatch.failedList.add(testAccount[0].Id);

        Test.startTest();
            Database.executeBatch(paymentBatch,2);
        Test.stopTest();

        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c];

        System.assertEquals(1, errorLogs.size(), 'Should have one error log created');
    }
}