force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <inlineHelpText>Date membership associated with this donation expired (if blank, membership is still active)</inlineHelpText>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_End_Date__c</fullName>
    <description>Monthly: End of the month following the most recent payment. One Time:  End of month following 12 months from Oppty close date.</description>
    <inlineHelpText>Date membership benefits for this donation are projected to expire if subsequent payment is not processed</inlineHelpText>
    <label>Projected End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MembershipExpirationBatchTest.cls
@IsTest
public class MembershipExpirationBatchTest {
    
    static testMethod void testMembershipExpirationBatch() {
        List<Account> accounts = TestUtilities.createAccounts(5, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        contacts = [SELECT Id, AccountId FROM Contact];
        List<Opportunity> activeOpps = TestUtilities.createOpportunities(contacts, 1, false);
        for (Integer i = 0; i < activeOpps.size(); i++) {
            activeOpps[i].Is_Monthly__c = (Math.mod(i, 2) == 0);
            activeOpps[i].Membership_Active__c = true;
            activeOpps[i].Projected_End_Date__c = Date.today() + 5;
        }
        List<Opportunity> oppsToExpire = TestUtilities.createOpportunities(contacts, 1, false);
        for (Integer i = 0; i < oppsToExpire.size(); i++) {
            oppsToExpire[i].Is_Monthly__c = (Math.mod(i, 2) == 0);
            oppsToExpire[i].Membership_Active__c = true;
            oppsToExpire[i].Projected_End_Date__c = Date.today() - 5;
        }
        List<Opportunity> allOpps = new List<Opportunity>(activeOpps);
        allOpps.addAll(oppsToExpire);
        insert allOpps;

        Test.startTest();
            Database.executeBatch(new MembershipExpirationBatch(), 200);
        Test.stopTest();

        List<Opportunity> updatedActiveOpps = [SELECT Id, Membership_Active__c, Is_Monthly__c, End_Reason__c, Actual_End_Date__c, Projected_End_Date__c
                                                            FROM Opportunity WHERE Id IN :activeOpps];
        List<Opportunity> updatedOppsToExpire = [SELECT Id, Membership_Active__c, Is_Monthly__c, End_Reason__c, Actual_End_Date__c, Projected_End_Date__c
                                                            FROM Opportunity WHERE Id IN :oppsToExpire];
        for (Opportunity anOpp : updatedActiveOpps) {
            System.assertEquals(null, anOpp.Actual_End_Date__c,
                'Expect Opporunities whose projected end dates are not in the past to not have an actual end date');
            System.assertEquals(true, anOpp.Membership_Active__c,
                'Expect Opporunities whose projected end dates are not in the past to have their membership active flag be checked');
         }
        for (Opportunity anOpp : updatedOppsToExpire) {
            System.assertNotEquals(null, anOpp.Actual_End_Date__c,
                'Expect Opporunities that expired to have an actual end date');
            System.assertEquals(false, anOpp.Membership_Active__c,
                'Expect opportunities that expire to have a membership_active of false');
            if (anOpp.Is_Monthly__c) {
                System.assertEquals(MembershipUtilities.END_REASON_SUSTAINER_DEFAULT, anOpp.End_Reason__c,
                    'Expect the opps end reason to reflect the default for sustainer opportunities');
            }
            else {
                System.assertEquals(MembershipUtilities.END_REASON_ONE_TIME_DEFAULT, anOpp.End_Reason__c,
                    'Expect the opps end reason to reflect the default for one time opportunities');
            }
        }

        
    }

    static testMethod void testDatabaseFailure() {
        List<Account> accounts = TestUtilities.createAccounts(5, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        contacts = [SELECT Id, AccountId FROM Contact];
        
        List<Opportunity> activeOpps = TestUtilities.createOpportunities(contacts, 1, false);
        for (Integer i = 0; i < activeOpps.size(); i++) {
            activeOpps[i].Is_Monthly__c = (Math.mod(i, 2) == 0);
            activeOpps[i].Membership_Active__c = true;
            activeOpps[i].Projected_End_Date__c = Date.today() + 5;
        }
        List<Opportunity> oppsToExpire = TestUtilities.createOpportunities(contacts, 1, false);
        for (Integer i = 0; i < oppsToExpire.size(); i++) {
            oppsToExpire[i].Is_Monthly__c = (Math.mod(i, 2) == 0);
            oppsToExpire[i].Membership_Active__c = true;
            oppsToExpire[i].Projected_End_Date__c = Date.today() - 5;
        }
        List<Opportunity> allOpps = new List<Opportunity>(activeOpps);
        allOpps.addAll(oppsToExpire);
        insert allOpps;

        MembershipExpirationBatch meb = new MembershipExpirationBatch();
        meb.failedMembershipReasons.add('Test reason');

        Test.startTest();
            Database.executeBatch(meb, 200);
        Test.stopTest();

        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c];

        System.assertEquals(1, errorLogs.size(), 'Should have one error log created');
        
    }
}