force-app/main/default/objects/Batch_Order__c/Batch_Order__c.object-meta.xml
<CustomObject>
    <label>Batch Order</label>
    <nameField>
        <displayFormat>BO-{0000}</displayFormat>
        <label>Batch Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
                <default>true</default>
                <label>Generated</label>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Batch_Order__c.field-meta.xml
<CustomField>
    <fullName>Batch_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The order export in which this gift can be found (if blank, fulfillment has not begun)</inlineHelpText>
    <label>Batch Order</label>
    <referenceTo>Batch_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchOrderTriggerHandlerTest.cls
@IsTest
public with sharing class BatchOrderTriggerHandlerTest {
    
    @testSetup
    static void testSetup() {
        final Integer NUM_OPPORTUNITIES = 10;
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Account> testVendor = TestUtilities.createVendors(1, true);
        List<Opportunity> testOpps = TestUtilities.createOpportunities(testAccount, NUM_OPPORTUNITIES, true);
        List<Product2> testProducts = TestUtilities.createProducts(NUM_OPPORTUNITIES, testVendor[0].Id, true);
        List<PricebookEntry> pbes = [SELECT Id FROM PricebookEntry WHERE Product2Id IN :testProducts AND Pricebook2Id = :Test.getStandardPricebookId()];
        List<OpportunityLineItem> testOlis = TestUtilities.createOpportunityLineItems(testOpps, pbes, NUM_OPPORTUNITIES, true);
    }

    static testMethod void testUpdateRelatedOliStatus() {
        List<OpportunityLineItem> olis = [SELECT Id FROM OpportunityLineItem];
        Batch_Order__c testBatchOrder = new Batch_Order__c();
        insert testBatchOrder;
        for (OpportunityLineItem anOli : olis) {
            anOli.Batch_Order__c = testBatchOrder.Id;
            anOli.Order_Status__c = 'Generated';
        }
        update olis;
        testBatchOrder.Status__c = 'Sent to Vendor';
        Test.startTest();
            update testBatchOrder;
        Test.stopTest();
        List<OpportunityLineItem> requeriedOlis = [SELECT Id, Order_Status__c FROM OpportunityLineItem WHERE Id IN :olis];
        for (OpportunityLineItem anOli : requeriedOlis) {
            System.assertEquals(testBatchOrder.Status__c, anOli.Order_Status__c, 'Expect all child OLI statuses to update to the parent batch order\'s status');
        }
    }
}