force-app/main/default/objects/Batch_Order__c/Batch_Order__c.object-meta.xml
<CustomObject>
    <label>Batch Order</label>
    <nameField>
        <displayFormat>BO-{0000}</displayFormat>
        <label>Batch Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
                <default>true</default>
                <label>Generated</label>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Batch_Order__c.field-meta.xml
<CustomField>
    <fullName>Batch_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The order export in which this gift can be found (if blank, fulfillment has not begun)</inlineHelpText>
    <label>Batch Order</label>
    <referenceTo>Batch_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchOrderTriggerHandler.cls
public class BatchOrderTriggerHandler extends TriggerHandler{
    
    public override void afterUpdate() {
        Map<Id,Batch_Order__c> filteredBatchOrders = filterBatchOrdersByStatusUpdate((List<Batch_Order__c>)Trigger.new, (Map<Id,Batch_Order__c>)Trigger.oldMap);
        if (!filteredBatchOrders.isEmpty()) {
            updateOpportunityProductStatuses(filteredBatchOrders);
        }
    }

    @TestVisible
    private Map<Id,Batch_Order__c> filterBatchOrdersByStatusUpdate(List<Batch_Order__c> triggerNew, Map<Id,Batch_Order__c> triggerOldMap) {
        Map<Id,Batch_Order__c> filteredBatchOrders = new Map<Id,Batch_Order__c>();
        for (Batch_Order__c aBatchOrder : triggerNew) {
            if (aBatchOrder.Status__c != triggerOldMap.get(aBatchOrder.Id).Status__c) {
                filteredBatchOrders.put(aBatchOrder.Id, aBatchOrder);
            }
        }
        return filteredBatchOrders;
    }

    @TestVisible
    private void updateOpportunityProductStatuses(Map<Id, Batch_Order__c> batchOrders) {
        List<OpportunityLineItem> allOlis = [
            SELECT Id, Batch_Order__c FROM OpportunityLineItem
            WHERE Batch_Order__c IN :batchOrders.keySet()
        ];
        Map<Id,List<OpportunityLineItem>> orderToLineItemMap = GroupBy.ids('Batch_Order__c', allOlis);
        for (Id aBatchOrderId : orderToLineItemMap.keySet()) {
            for (OpportunityLineItem anOli : orderToLineItemMap.get(aBatchOrderId)) {
                anOLI.Order_Status__c = batchOrders.get(aBatchOrderId).Status__c;
            }
        }
        try {
            update allOlis;
        }
        catch (DMLException e) {
            for (Integer i = 0; i < e.getNumDml(); i++) {
                Batch_Order__c failedBatchOrder = batchOrders.get(allOlis[e.getDmlIndex(i)].Batch_Order__c);
                failedBatchOrder.addError(e.getDmlMessage(i));
            }
        }
    }
}