force-app/main/default/objects/Product_Order_Template__c/Product_Order_Template__c.object-meta.xml
<CustomObject>
    <description>A list of data elements associated with a product order.  The product order itself is an Opportunity Line Item record that is associated with an Opportunity, a Contact, and a Product (Product2) record.</description>
    <label>Product Order Template</label>
    <nameField>
        <label>Product Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/Product_Template_Field__c.object-meta.xml
<CustomObject>
    <description>This represents the selection of a field on either the Product (Product2), Opportunity Line Item, Opportunity, or Contact object.</description>
    <label>Product Template Field</label>
    <nameField>
        <displayFormat>PTF-{000000}</displayFormat>
        <label>Product Template Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>This is the list of the fields that one can pick from in order to create a template.

NOTE: The picklist values in this field must be kept in sync with the Field Name values in the custom metadata type named Product Template Name Map.</description>
    <label>Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opp Product: Id</fullName>
            </value>
            <value>
                <fullName>Opp Product: Name</fullName>
            </value>
            <value>
                <fullName>Opp Product: ProductCode</fullName>
            </value>
            <value>
                <fullName>Opp Product: Quantity</fullName>
            </value>
            <value>
                <fullName>Opp Product: Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Created Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Last Mod Date</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Street</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping City</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping State</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Postal Code</fullName>
            </value>
            <value>
                <fullName>Contact: First Name</fullName>
            </value>
            <value>
                <fullName>Contact: Last Name</fullName>
            </value>
            <value>
                <fullName>Contact: Email</fullName>
            </value>
            <value>
                <fullName>Product: Id</fullName>
            </value>
            <value>
                <fullName>Product: Available To Ship Date</fullName>
            </value>
            <value>
                <fullName>Product: Cost</fullName>
            </value>
            <value>
                <fullName>Product: Distributor</fullName>
            </value>
            <value>
                <fullName>Product: Estimated Ship Time</fullName>
            </value>
            <value>
                <fullName>Product: Generic Product</fullName>
            </value>
            <value>
                <fullName>Product: Product Code</fullName>
            </value>
            <value>
                <fullName>Product: Stock Keeping Unit</fullName>
            </value>
            <value>
                <fullName>Product: Shipping Method</fullName>
            </value>
            <value>
                <fullName>Product: Type</fullName>
            </value>
            <value>
                <fullName>Opportunity: Id</fullName>
            </value>
            <value>
                <fullName>Opportunity: Account Number</fullName>
            </value>
            <value>
                <fullName>Opportunity: Close Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <description>Determines the placement of this field within the Product Order Template.</description>
    <inlineHelpText>Index of field column when exported to Excel</inlineHelpText>
    <label>Field Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <description>Determines the template that this particular field is associated with.</description>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Product Template Fields</relationshipLabel>
    <relationshipName>Product_Template_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductTemplateFieldTriggerHandler.cls
public with sharing class ProductTemplateFieldTriggerHandler extends TriggerHandler {

    public override void beforeInsert() {
        checkForDuplicatesInsert((List<Product_Template_Field__c>)Trigger.new);
    }

    public override void beforeUpdate() {
        checkForDuplicatesUpdate(((List<Product_Template_Field__c>)Trigger.old), ((List<Product_Template_Field__c>)Trigger.new)); 
    }

    private void checkForDuplicatesInsert(List<Product_Template_Field__c> thePTFs) {
        // Only validate single-row inserts. The code is not bulk-safe
        if (thePTFs.size() > 1) return;

        List<Product_Template_Field__c> existingPTFs = new List<Product_Template_Field__c>([SELECT Id
                FROM Product_Template_Field__c 
                    WHERE (Field_Order__c = :thePTFs[0].Field_Order__c OR
                            Field_Name__c = :thePTFs[0].Field_Name__c)
                    AND Product_Order_Template__c = :thePTFs[0].Product_Order_Template__c]);
        If (existingPTFs.size() > 0) {
            thePTFs[0].AddError('Neither the Field Name nor the Field Order can already be present for this template.');
        }
    
    }

    private void checkForDuplicatesUpdate(List<Product_Template_Field__c> oldPTFs, List<Product_Template_Field__c> newPTFs) {
       // Only validate single-row updates. The code is not bulk-safe
        if (newPTFs.size() > 1) return;

        List<Product_Template_Field__c> existingPTFs = new List<Product_Template_Field__c>();
        
        // Need to determine what has been changed and query appropriately
        if (oldPTFs[0].Field_Order__c != newPTFs[0].Field_Order__c) {  // Order has been changed
            if (oldPTFs[0].Field_Name__c != newPTFs[0].Field_Name__c) {  // Order AND Field Name have been changed
                existingPTFs = ([SELECT Id FROM Product_Template_Field__c 
                    WHERE (Field_Order__c = :newPTFs[0].Field_Order__c OR
                            Field_Name__c = :newPTFs[0].Field_Name__c)
                        AND Product_Order_Template__c = :newPTFs[0].Product_Order_Template__c]);
            } else { // ONLY Field Order has changed
                existingPTFs = ([SELECT Id FROM Product_Template_Field__c 
                    WHERE Field_Order__c = :newPTFs[0].Field_Order__c
                        AND Product_Order_Template__c = :newPTFs[0].Product_Order_Template__c]);
            }
        } else {  //  Order has NOT been changed
            if (oldPTFs[0].Field_Name__c != newPTFs[0].Field_Name__c) {  // Only Field Name has been changed
                existingPTFs = ([SELECT Id FROM Product_Template_Field__c 
                    WHERE Field_Name__c = :newPTFs[0].Field_Name__c
                        AND Product_Order_Template__c = :newPTFs[0].Product_Order_Template__c]);
            } // Nothing will happen if nothing has changed.
        }

        If (existingPTFs != null && existingPTFs.size() > 0) {
            newPTFs[0].AddError('Neither the Field Name nor the Field Order can already be present for this template.');
        }

    }    

}