force-app/main/default/objects/Product_Order_Template__c/Product_Order_Template__c.object-meta.xml
<CustomObject>
    <description>A list of data elements associated with a product order.  The product order itself is an Opportunity Line Item record that is associated with an Opportunity, a Contact, and a Product (Product2) record.</description>
    <label>Product Order Template</label>
    <nameField>
        <label>Product Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/Product_Template_Field__c.object-meta.xml
<CustomObject>
    <description>This represents the selection of a field on either the Product (Product2), Opportunity Line Item, Opportunity, or Contact object.</description>
    <label>Product Template Field</label>
    <nameField>
        <displayFormat>PTF-{000000}</displayFormat>
        <label>Product Template Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>This is the list of the fields that one can pick from in order to create a template.

NOTE: The picklist values in this field must be kept in sync with the Field Name values in the custom metadata type named Product Template Name Map.</description>
    <label>Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opp Product: Id</fullName>
            </value>
            <value>
                <fullName>Opp Product: Name</fullName>
            </value>
            <value>
                <fullName>Opp Product: ProductCode</fullName>
            </value>
            <value>
                <fullName>Opp Product: Quantity</fullName>
            </value>
            <value>
                <fullName>Opp Product: Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Created Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Last Mod Date</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Street</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping City</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping State</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Postal Code</fullName>
            </value>
            <value>
                <fullName>Contact: First Name</fullName>
            </value>
            <value>
                <fullName>Contact: Last Name</fullName>
            </value>
            <value>
                <fullName>Contact: Email</fullName>
            </value>
            <value>
                <fullName>Product: Id</fullName>
            </value>
            <value>
                <fullName>Product: Available To Ship Date</fullName>
            </value>
            <value>
                <fullName>Product: Cost</fullName>
            </value>
            <value>
                <fullName>Product: Distributor</fullName>
            </value>
            <value>
                <fullName>Product: Estimated Ship Time</fullName>
            </value>
            <value>
                <fullName>Product: Generic Product</fullName>
            </value>
            <value>
                <fullName>Product: Product Code</fullName>
            </value>
            <value>
                <fullName>Product: Stock Keeping Unit</fullName>
            </value>
            <value>
                <fullName>Product: Shipping Method</fullName>
            </value>
            <value>
                <fullName>Product: Type</fullName>
            </value>
            <value>
                <fullName>Opportunity: Id</fullName>
            </value>
            <value>
                <fullName>Opportunity: Account Number</fullName>
            </value>
            <value>
                <fullName>Opportunity: Close Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <description>Determines the placement of this field within the Product Order Template.</description>
    <inlineHelpText>Index of field column when exported to Excel</inlineHelpText>
    <label>Field Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <description>Determines the template that this particular field is associated with.</description>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Product Template Fields</relationshipLabel>
    <relationshipName>Product_Template_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductTemplateFieldTriggerHandlerTest.cls
@IsTest
private class ProductTemplateFieldTriggerHandlerTest {
    
    @testSetup 
    static void testSetup() {
        Product_Order_Template__c testPOT = new Product_Order_Template__c(Name = 'testPOT',
            Active__c = true);
        insert testPOT;

        Product_Template_Field__c testPTF1 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Id', 
                Field_Order__c = 1, Product_Order_Template__c = testPOT.Id);    
        Product_Template_Field__c testPTF2 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Name', 
                Field_Order__c = 2, Product_Order_Template__c = testPOT.Id);    
        Product_Template_Field__c testPTF3 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Quantity', 
                Field_Order__c = 3, Product_Order_Template__c = testPOT.Id);    
        Product_Template_Field__c testPTF4 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Date', 
                Field_Order__c = 4, Product_Order_Template__c = testPOT.Id);    
        insert new List<Product_Template_Field__c>{testPTF1, testPTF2, testPTF3, testPTF4};
    }
    
    static testMethod void testGoodInsert() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c newPTF = new Product_Template_Field__c(Field_Name__c = 'Contact: Email', 
            Field_Order__c = 5, Product_Order_Template__c = testPOT.Id);    
        
        Test.startTest();

        Database.SaveResult sr = Database.insert(newPTF, false);
        
        Test.stopTest();

        System.assert(sr.isSuccess(), 'Insert should happen without error.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Id != null]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(5, numOfPTFs, 'There should be 5 Product Template Fields at this point.');
    }

    static testMethod void testBadInsert_Order() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c newPTF = new Product_Template_Field__c(Field_Name__c = 'Contact: Email', 
            Field_Order__c = 3, Product_Order_Template__c = testPOT.Id);    
        
        Test.startTest();
        
        Database.SaveResult sr = Database.insert(newPTF, false);

        Test.stopTest();

        System.assert(!sr.isSuccess(), 'Insert should NOT happen.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Id != null]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(4, numOfPTFs, 'There should be 4 Product Template Fields at this point.');
    }

    static testMethod void testBadInsert_Field() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c newPTF = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Id', 
            Field_Order__c = 5, Product_Order_Template__c = testPOT.Id);    
        
        Test.startTest();

        Database.SaveResult sr = Database.insert(newPTF, false);

        Test.stopTest();

        System.assert(!sr.isSuccess(), 'Insert should NOT happen.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Id != null]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(4, numOfPTFs, 'There should be 4 Product Template Fields at this point.');
    }

    static testMethod void testGoodUpdate_Order() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c existingPTF = [SELECT Id FROM Product_Template_Field__c 
            WHERE Field_Order__c = 1 LIMIT 1];
        
        existingPTF.Field_Order__c = 5;    
        
        Test.startTest();

        Database.SaveResult sr = Database.update(existingPTF, false);

        Test.stopTest();

        System.assert(sr.isSuccess(), 'Update should happen successfully.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Field_Order__c = 5]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(1, numOfPTFs, 'There should be a test PTF that now has Field Order 5.');
    }

    static testMethod void testGoodUpdate_Field() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c existingPTF = [SELECT Id FROM Product_Template_Field__c 
            WHERE Field_Name__c = 'Opp Product: Name' LIMIT 1];
        
        ExistingPTF.Field_Name__c = 'Contact: Email';    
        
        Test.startTest();

        Database.SaveResult sr = Database.update(existingPTF, false);

        Test.stopTest();

        System.assert(sr.isSuccess(), 'Update should happen successfully.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Field_Name__c = 'Contact: Email']);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(1, numOfPTFs, 'There should be a test PTF that now has Field Name \'Contact: Email\'.');
    }

    static testMethod void testGoodUpdate_OrderAndField() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c existingPTF = [SELECT Id FROM Product_Template_Field__c 
            WHERE Field_Name__c = 'Opp Product: Name' LIMIT 1];
        
        ExistingPTF.Field_Name__c = 'Contact: Email';
        ExistingPTF.Field_Order__c = 5;    
        
        Test.startTest();
        
        Database.SaveResult sr = Database.update(existingPTF, false);

        Test.stopTest();

        System.assert(sr.isSuccess(), 'Update should happen successfully.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Field_Name__c = 'Contact: Email'
                AND Field_Order__c = 5]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(1, numOfPTFs, 'One PTF has Field Name = \'Contact: Email\' and Field Order = 5.');
    }

    static testMethod void testBadUpdate_Order() {
    
        Product_Order_Template__c testPOT = [SELECT Id FROM Product_Order_Template__c LIMIT 1];
        
        Product_Template_Field__c existingPTF = [SELECT Id FROM Product_Template_Field__c 
            WHERE Field_Order__c = 1 LIMIT 1];
        
        ExistingPTF.Field_Order__c = 2;    

        Test.startTest();

        Database.SaveResult sr = Database.update(existingPTF, false);

        Test.stopTest();

        System.assert(!sr.isSuccess(), 'Update should NOT happen successfully.');

        List<Product_Template_Field__c> testPTFs = new List<Product_Template_Field__c>([SELECT Id 
                FROM Product_Template_Field__c WHERE Field_Order__c = 2]);
        Integer numOfPTFs = testPTFs.size();

        System.assertEquals(1, numOfPTFs, 'Only 1 PTF should have Field Order = 2.');
    }
}