force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <label>Member Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/Member_Benefit_Level__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Level</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>Member Level Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefit Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Level__c.field-meta.xml
<CustomField>
    <fullName>Member_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Level</label>
    <referenceTo>Member_Level__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Level__c/Member_Level__c.object-meta.xml
<CustomObject>
    <label>Member Level</label>
    <nameField>
        <label>Member Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Level__c/fields/Member_Level_Value__c.field-meta.xml
<CustomField>
    <fullName>Member_Level_Value__c</fullName>
    <inlineHelpText>The amount of annual donations needed to be considered for this level.  The donations consist of monthly giving (annualized) and one time donations within the last year.</inlineHelpText>
    <label>Member Level Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MembershipBenefitLevelTriggerHandlerTest.cls
@IsTest
private class MembershipBenefitLevelTriggerHandlerTest {
    
    static testMethod void testGoodInsert() {
    
        Member_Benefit__c mb1 = new Member_Benefit__c (Name = 'Benefit 1', Description__c = 'Benefit 1');
        Member_Benefit__c mb2 = new Member_Benefit__c (Name = 'Benefit 2', Description__c = 'Benefit 2');
        insert new List<Member_Benefit__c>{mb1, mb2};            
        
        Member_Level__c ml1 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 100);
        Member_Level__c ml2 = new Member_Level__c (Name = 'Level 2', Member_Level_Value__c = 200);
        insert new List<Member_Level__c>{ml1, ml2};            
        
        Member_Benefit_Level__c mbl1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);
        Member_Benefit_Level__c mbl2 = new Member_Benefit_Level__c(Member_Benefit__c = mb2.Id, Member_Level__c = ml2.Id);
        insert new List<Member_Benefit_Level__c>{mbl1, mbl2};   
        
        Member_Benefit_Level__c newMBL1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml2.Id);    
        Member_Benefit_Level__c newMBL2 = new Member_Benefit_Level__c(Member_Benefit__c = mb2.Id, Member_Level__c = ml1.Id);    
        
        Test.startTest();
            Database.SaveResult sr1 = Database.insert(newMBL1, false);
            Database.SaveResult sr2 = Database.insert(newMBL2, false);
        Test.stopTest();

        System.assert(sr1.isSuccess(), 'Insert of first MBL should happen without error.');
        System.assert(sr2.isSuccess(), 'Insert of second MBL should happen without error.');

        List<Member_Benefit_Level__c> testMBLs = new List<Member_Benefit_Level__c>([SELECT Id 
                FROM Member_Benefit_Level__c WHERE Id != null]);
        Integer numOfMBLs = testMBLs.size();

        System.assertEquals(4, numOfMBLs, 'There should be 4 Member Benefit Levels at this point.');
    }

    static testMethod void testBadInsert() {

        Member_Benefit__c mb1 = new Member_Benefit__c (Name = 'Benefit 1', Description__c = 'Benefit 1');
        insert new List<Member_Benefit__c>{mb1};            
        
        Member_Level__c ml1 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 100);
        insert new List<Member_Level__c>{ml1};            
        
        Member_Benefit_Level__c mbl1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);
        insert new List<Member_Benefit_Level__c>{mbl1};   
        
        Member_Benefit_Level__c newMBL1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);    
        
        Test.startTest();
            Database.SaveResult sr = Database.insert(newMBL1, false);
        Test.stopTest();

        System.assert(!sr.isSuccess(), 'Insert should NOT happen.');

        List<Member_Benefit_Level__c> testMBLs = new List<Member_Benefit_Level__c>([SELECT Id 
                FROM Member_Benefit_Level__c WHERE Id != null]);
        Integer numOfMBLs = testMBLs.size();

        System.assertEquals(1, numOfMBLs, 'There should be 1 Member Benefit Levels at this point.');

    }

    static testMethod void testGoodUpdate() {
    
        Member_Benefit__c mb1 = new Member_Benefit__c (Name = 'Benefit 1', Description__c = 'Benefit 1');
        Member_Benefit__c mb2 = new Member_Benefit__c (Name = 'Benefit 2', Description__c = 'Benefit 2');
        insert new List<Member_Benefit__c>{mb1, mb2};            
        
        Member_Level__c ml1 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 100);
        Member_Level__c ml2 = new Member_Level__c (Name = 'Level 2', Member_Level_Value__c = 200);
        insert new List<Member_Level__c>{ml1, ml2};            
        
        Member_Benefit_Level__c mbl1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);
        Member_Benefit_Level__c mbl2 = new Member_Benefit_Level__c(Member_Benefit__c = mb2.Id, Member_Level__c = ml2.Id);
        insert new List<Member_Benefit_Level__c>{mbl1, mbl2};   
        
        mbl1.Member_Benefit__c = mb2.Id;
        mbl2.Member_Benefit__c = mb1.Id;

        Test.startTest();
            Database.SaveResult sr1 = Database.update(mbl1, false);
            Database.SaveResult sr2 = Database.update(mbl2, false);
        Test.stopTest();
        
        System.assert(sr1.isSuccess(), 'First update should happen without error.');
        System.assert(sr2.isSuccess(), 'Second update should happen without error.');

    }

    static testMethod void testBadUpdate() {
    
        Member_Benefit__c mb1 = new Member_Benefit__c (Name = 'Benefit 1', Description__c = 'Benefit 1');
        Member_Benefit__c mb2 = new Member_Benefit__c (Name = 'Benefit 2', Description__c = 'Benefit 2');
        insert new List<Member_Benefit__c>{mb1, mb2};            
        
        Member_Level__c ml1 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 100);
        Member_Level__c ml2 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 200);
        insert new List<Member_Level__c>{ml1, ml2};            
        
        Member_Benefit_Level__c mbl1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);
        Member_Benefit_Level__c mbl2 = new Member_Benefit_Level__c(Member_Benefit__c = mb2.Id, Member_Level__c = ml2.Id);
        insert new List<Member_Benefit_Level__c>{mbl1, mbl2};   
        
        mbl2.Member_Benefit__c = mb1.Id;
        mbl2.Member_Level__c = ml1.Id;

        Test.startTest();
            Database.SaveResult sr = Database.update(mbl2, false);
        Test.stopTest();
        
        System.assert(!sr.isSuccess(), 'Update should NOT happen without error.');

    }

}