force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <label>Member Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/Member_Benefit_Level__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Level</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>Member Level Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefit Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Level__c.field-meta.xml
<CustomField>
    <fullName>Member_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Level</label>
    <referenceTo>Member_Level__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Level__c/Member_Level__c.object-meta.xml
<CustomObject>
    <label>Member Level</label>
    <nameField>
        <label>Member Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MemberBenefitLevelTriggerHandler.cls
public with sharing class MemberBenefitLevelTriggerHandler extends TriggerHandler {

    public override void beforeInsert() {
        checkForDuplicatesInsert((List<Member_Benefit_Level__c>)Trigger.new);
    }

    public override void beforeUpdate() {
        checkForDuplicatesUpdate(((List<Member_Benefit_Level__c>)Trigger.old), ((List<Member_Benefit_Level__c>)Trigger.new)); 
    }

    private void checkForDuplicatesInsert(List<Member_Benefit_Level__c> theMBLs) {
        // Only validate single-row inserts. The code is not bulk-safe
        if (theMBLs.size() > 1) return;

        List<Member_Benefit_Level__c> existingMBLs = new List<Member_Benefit_Level__c>([SELECT Id
                FROM Member_Benefit_Level__c 
                WHERE Member_Benefit__c = :theMBLs[0].Member_Benefit__c 
                AND Member_Level__c = :theMBLs[0].Member_Level__c]);
        If (existingMBLs.size() > 0) {
            theMBLs[0].AddError('A Member Benefit Level with this Level and this Benefit already exists.');
        }
    }

    private void checkForDuplicatesUpdate(List<Member_Benefit_Level__c> oldMBLs, List<Member_Benefit_Level__c> newMBLs) {
       // Only validate single-row updates. The code is not bulk-safe
        if (newMBLs.size() > 1) return;

        List<Member_Benefit_Level__c> existingMBLs = new List<Member_Benefit_Level__c>();

        existingMBLs = ([SELECT Id FROM Member_Benefit_Level__c 
                WHERE Member_Level__c = :newMBLs[0].Member_Level__c 
                AND Member_Benefit__c = :newMBLs[0].Member_Benefit__c]);

        if (existingMBLs != null && existingMBLs.size() > 0) {
            newMBLs[0].AddError('A Member Benefit Level with this Level and this Benefit already exists.');
        }
    }    

}