force-app/main/default/objects/Product2/fields/ACD_Name__c.field-meta.xml
<CustomField>
    <fullName>ACD_Name__c</fullName>
    <label>ACD Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_to_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Ship_Date__c</fullName>
    <label>Available to Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estimated_Shipping_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Shipping_Time__c</fullName>
    <label>Estimated Shipping Time</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Live_On_Web__c.field-meta.xml
<CustomField>
    <fullName>Live_On_Web__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when a Premium is live in the web store</description>
    <inlineHelpText>If checked, premium is live in the web gateway and can be selected by donors</inlineHelpText>
    <label>Live on Web</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/One_Time_Price__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Price__c</fullName>
    <label>One Time Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Product_Specifications__c</fullName>
    <label>Product Specifications</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DVD</fullName>
            </value>
            <value>
                <fullName>Bluray</fullName>
            </value>
            <value>
                <fullName>Hardcover</fullName>
            </value>
            <value>
                <fullName>Softcover</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Legal Services</fullName>
            </value>
            <value>
                <fullName>Retirement Planning</fullName>
            </value>
            <value>
                <fullName>Identity Theft Protection</fullName>
            </value>
            <value>
                <fullName>Mug</fullName>
            </value>
            <value>
                <fullName>Backpack</fullName>
            </value>
            <value>
                <fullName>Tote</fullName>
            </value>
            <value>
                <fullName>T-Shirt</fullName>
            </value>
            <value>
                <fullName>Hoodie</fullName>
            </value>
            <value>
                <fullName>Emergency Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sustainer_Price__c.field-meta.xml
<CustomField>
    <fullName>Sustainer_Price__c</fullName>
    <label>Sustainer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tagline__c.field-meta.xml
<CustomField>
    <fullName>Tagline__c</fullName>
    <inlineHelpText>Appears below name of premium in web gateway</inlineHelpText>
    <label>Tagline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>Book</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Perishables</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Music Service</fullName>
            </value>
            <value>
                <fullName>Video Service</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Schedule__c/Product_Schedule__c.object-meta.xml
<CustomObject>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Schedule__c/fields/One_Time_Price__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Price__c</fullName>
    <formula>Product__r.One_Time_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>One Time Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product is not live on web. Please select different product.</errorMessage>
        <filterItems>
            <field>Product2.Live_On_Web__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage></infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Schedules</relationshipLabel>
    <relationshipName>Product_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Schedule__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <inlineHelpText>KQED fiscal quarter</inlineHelpText>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Schedule__c/fields/Sustainer_Price__c.field-meta.xml
<CustomField>
    <fullName>Sustainer_Price__c</fullName>
    <formula>Product__r.Sustainer_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sustainer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductTilesController.cls
public class ProductTilesController {

    public static Integer getFiscalQuarter(Integer orgFiscalStartMonth, Integer currentMonth) {
        currentMonth = currentMonth - orgFiscalStartMonth;
        if (currentMonth < 0) currentMonth += 12;
        Decimal currentFiscalQuarter = Math.floor(currentMonth / 3) + 1; // quarters start at index 1
        return Integer.valueOf(currentFiscalQuarter);
    }

    public static List<Product_Schedule__c> getCurrentProductSchedules() {
        Organization fiscalYearDetails = [SELECT FiscalYearStartMonth, UsesStartDateAsFiscalYearName FROM Organization];
        Integer orgFiscalStartMonth = fiscalYearDetails.FiscalYearStartMonth;
        Integer currentMonth = Date.today().month();
        Integer currentQuarter = getFiscalQuarter(orgFiscalStartMonth, currentMonth);
        Integer currentYear;
        if (currentMonth >= orgFiscalStartMonth) {
            currentYear = fiscalYearDetails.UsesStartDateAsFiscalYearName ? Date.today().year() : Date.today().year() + 1;
        }
        else {
            currentYear = fiscalYearDetails.UsesStartDateAsFiscalYearName ? Date.today().year() + 1 : Date.today().year();
        }
        return [
            SELECT Product__c
            FROM Product_Schedule__c
            WHERE
                Quarter__c = :String.valueOf(currentQuarter) AND
                Fiscal_Year__c = :String.valueOf(currentYear)
        ];
    }

    @AuraEnabled
    public static Map<Boolean,List<Product2>> getQualifyingProducts() {
        List<Product_Schedule__c> schedules = getCurrentProductSchedules();
        Set<Id> scheduledProductIds = Pluck.ids('Product__c', schedules);
        
        String baseQuery = 'SELECT Id, Name, ACD_Name__c, Type__c, Sub_Type__c, Product_Specifications__c,'
                            +    ' Image_URL__c, Tagline__c, One_Time_Price__c, Sustainer_Price__c, Description__c,'
                            +    ' Available_to_Ship_Date__c, Estimated_Shipping_Time__c, Live_on_Web__c '
                            + 'FROM Product2 ' 
                            + 'WHERE Live_on_Web__c = true ';
        List<Product2> otProducts = Database.query(baseQuery + ' AND Id IN :scheduledProductIds AND One_Time_Price__c != null ORDER BY One_Time_Price__c DESC');
        otProducts.addAll((List<Product2>)Database.query(baseQuery + ' AND Id NOT IN :scheduledProductIds AND One_Time_Price__c != null ORDER BY One_Time_Price__c DESC'));
        List<Product2> sgProducts = Database.query(baseQuery + ' AND Id IN :scheduledProductIds AND Sustainer_Price__c != null ORDER BY Sustainer_Price__c DESC');
        sgProducts.addAll((List<Product2>)Database.query(baseQuery + ' AND Id NOT IN :scheduledProductIds AND Sustainer_Price__c != null ORDER BY Sustainer_Price__c DESC'));
        Map<Boolean,List<Product2>> returnMap = new Map<Boolean,List<Product2>>();
        returnMap.put(true, sgProducts);
        returnMap.put(false, otProducts);
        return returnMap;
    }
}