force-app/main/default/objects/Account/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Product Order Template: The preferred format for order exports generated for this vendor</inlineHelpText>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Order__c/Batch_Order__c.object-meta.xml
<CustomObject>
    <label>Batch Order</label>
    <nameField>
        <displayFormat>BO-{0000}</displayFormat>
        <label>Batch Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact responsible for this donation, if applicable</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Postal_Code__c</fullName>
    <label>Shipping Postal Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State__c</fullName>
    <label>Shipping State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Batch_Order__c.field-meta.xml
<CustomField>
    <fullName>Batch_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The order export in which this gift can be found (if blank, fulfillment has not begun)</inlineHelpText>
    <label>Batch Order</label>
    <referenceTo>Batch_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_to_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Ship_Date__c</fullName>
    <label>Available to Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Cost to KQED</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products (Distributor)</relationshipLabel>
    <relationshipName>Distributed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estimated_Shipping_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Shipping_Time__c</fullName>
    <label>Estimated Shipping Time</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ship from warehouse</fullName>
            </value>
            <value>
                <fullName>Drop ship</fullName>
            </value>
            <value>
                <fullName>In-house distribution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>Book</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Perishables</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Music Service</fullName>
            </value>
            <value>
                <fullName>Video Service</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Order_Template__c/Product_Order_Template__c.object-meta.xml
<CustomObject>
    <description>A list of data elements associated with a product order.  The product order itself is an Opportunity Line Item record that is associated with an Opportunity, a Contact, and a Product (Product2) record.</description>
    <label>Product Order Template</label>
    <nameField>
        <label>Product Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/Product_Template_Field__c.object-meta.xml
<CustomObject>
    <description>This represents the selection of a field on either the Product (Product2), Opportunity Line Item, Opportunity, or Contact object.</description>
    <label>Product Template Field</label>
    <nameField>
        <displayFormat>PTF-{000000}</displayFormat>
        <label>Product Template Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>This is the list of the fields that one can pick from in order to create a template.

NOTE: The picklist values in this field must be kept in sync with the Field Name values in the custom metadata type named Product Template Name Map.</description>
    <label>Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opp Product: Id</fullName>
            </value>
            <value>
                <fullName>Opp Product: Name</fullName>
            </value>
            <value>
                <fullName>Opp Product: ProductCode</fullName>
            </value>
            <value>
                <fullName>Opp Product: Quantity</fullName>
            </value>
            <value>
                <fullName>Opp Product: Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Created Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Last Mod Date</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Street</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping City</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping State</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Postal Code</fullName>
            </value>
            <value>
                <fullName>Contact: First Name</fullName>
            </value>
            <value>
                <fullName>Contact: Last Name</fullName>
            </value>
            <value>
                <fullName>Contact: Email</fullName>
            </value>
            <value>
                <fullName>Product: Id</fullName>
            </value>
            <value>
                <fullName>Product: Available To Ship Date</fullName>
            </value>
            <value>
                <fullName>Product: Cost</fullName>
            </value>
            <value>
                <fullName>Product: Distributor</fullName>
            </value>
            <value>
                <fullName>Product: Estimated Ship Time</fullName>
            </value>
            <value>
                <fullName>Product: Generic Product</fullName>
            </value>
            <value>
                <fullName>Product: Product Code</fullName>
            </value>
            <value>
                <fullName>Product: Stock Keeping Unit</fullName>
            </value>
            <value>
                <fullName>Product: Shipping Method</fullName>
            </value>
            <value>
                <fullName>Product: Type</fullName>
            </value>
            <value>
                <fullName>Opportunity: Id</fullName>
            </value>
            <value>
                <fullName>Opportunity: Account Number</fullName>
            </value>
            <value>
                <fullName>Opportunity: Close Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <description>Determines the placement of this field within the Product Order Template.</description>
    <inlineHelpText>Index of field column when exported to Excel</inlineHelpText>
    <label>Field Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <description>Determines the template that this particular field is associated with.</description>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Product Template Fields</relationshipLabel>
    <relationshipName>Product_Template_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Template_Name_Map__mdt/Product_Template_Name_Map__mdt.object-meta.xml
<CustomObject>
    <description>This contains a map of String, String which represents the field label and the API name for the Field Name picklist on the Product Template Field object.

NOTE: The Field Label entries in this list must be kept in sync with the picklist values in the Field_Name__c field of the Product_Template_Field__c object.</description>
    <label>Product Template Name Map</label>
    <pluralLabel>Product Template Name Maps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Template_Name_Map__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>The field type of the field.  Need to know this when converting the field to a string.</description>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
                <default>true</default>
                <label>Date</label>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Template_Name_Map__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The field API Name to be used in queries selecting from Opportunity Line Item,  i.e. "Product2.Type".</description>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Template_Name_Map__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>The field label shown in the GUI, i.e. "Product: Type".</description>
    <label>Field Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchOrderCsvWriter.cls
public with sharing class BatchOrderCsvWriter implements Queueable {

    // NOTE: This code requires the manual synchronization of three items:
    //      - The code in the execute method below.
    //      - The picklist items in the field Product_Order_Template__c.Field_Name__c.
    //      - The items in the custom metadata object Product Template Name Map.
    // Additions to the picklist field must be accommodated in the other two locations to work properly.

    Id vendorId;
    String vendorName;
    Id productOrderTemplateId;
    List<OpportunityLineItem> olis;
    Id batchOrderId;

    public BatchOrderCsvWriter(Id vendorId, String vendorName, Id productOrderTemplateId, List<OpportunityLineItem> olis, Id batchOrderId) {
        this.vendorId = vendorId;
        this.vendorName = vendorName;
        this.productOrderTemplateId = productOrderTemplateId;
        this.batchOrderId = batchOrderId;
        this.olis = olis;
    }

    private List<OpportunityLineItem> requeryOlis(List<OpportunityLineItem> olis, List<Product_Template_Field__c> queryFields, Map<String,String> labelToApiName) {
        if (queryFields.size() < 1) {
            return null;
        }

        Set<String> queryFieldNames = new Set<String>{'Id'};
        for (Integer i = 0; i < queryFields.size(); i++) {
            if (labelToApiName.get(queryFields[i].Field_Name__c) != null) {
                queryFieldNames.add(labelToApiName.get(queryFields[i].Field_Name__c));
            }
        }

        // Begin constructing the query
        String query = 'SELECT ';
        query += String.join(new List<String>(queryFieldNames), ', ');
        query += ' FROM OpportunityLineItem ';
        query += ' WHERE Id IN :oliIds';

        Set<Id> oliIds = Pluck.ids(olis);
        return Database.query(query);
    }

    public void execute(QueueableContext qc) {
        String csvString = buildCsvString();
        if (String.isBlank(csvString)) {
            return;
        }
        Date thisDate = Date.today();
        String dateString = thisDate.month() + '_' + thisDate.day() + '_' + thisDate.year();
        String sanitizedVendorName = this.vendorName.replace(' ', '');  // Don't want spaces in the file name
        String contentName = sanitizedVendorName + '_' + dateString;

        // Create the ContentVersion which automatically creates and links to a ContentDocument
        ContentVersion cv = new ContentVersion(
            VersionData = Blob.valueOf(csvString),
            Title = contentName,
            PathOnClient = contentName + '.csv'
        );
        Savepoint sp = Database.setSavepoint();
        try {
            insert cv;
        }
        catch (DMLException e) {
            ErrorLog.logError(e, 'BatchOrderCsvWriter', 'Error inserting content version');
            ErrorLog.commitErrors();
            return;
        }
        ContentVersion requeriedCv = [
            SELECT Id, ContentDocumentId
            FROM ContentVersion
            WHERE Id = :cv.Id
        ];
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = requeriedCv.ContentDocumentId,
            LinkedEntityId = batchOrderId,
            ShareType = 'V'
        );
        try {
            insert cdl;
        }
        catch (DMLException e) {
            Database.rollback(sp);
            ErrorLog.logError(e, 'BatchOrderCsvWriter', 'Error inserting content document link');
            ErrorLog.commitErrors();
        }
        for (OpportunityLineItem anOli : olis) {
            anOli.Batch_Order__c = batchOrderId;
            anOli.Order_Status__c = OpportunityProductUtilities.GENERATED_ORDER_STATUS;
        }
        try {
            update olis;
        }
        catch (DMLException e) {
            Database.rollback(sp);
            ErrorLog.logError(e, 'BatchOrderCsvWriter', 'Error updating opportunity products');
            ErrorLog.commitErrors();
        }
    }

    private String buildCsvString() {
        List<Product_Template_Field__c> fieldsInTemplate = new List<Product_Template_Field__c>([
            SELECT Field_Name__c, Field_Order__c
                FROM Product_Template_Field__c
                WHERE Product_Order_Template__c	= :this.productOrderTemplateId
                ORDER BY Field_Order__c
        ]);
        if (fieldsInTemplate.isEmpty()) {
            return null;
        }

        // Creating two static maps from custom metadata object Product Template Name Map
        // First maps field labels to API name.  Second maps field labels to Data Type.
        Map<String, String> labelToApiName = new Map<String, String>();
        Map<String, String> labelToDataType = new Map<String, String>();

        Product_Template_Name_Map__mdt[] PTN_Mappings = [
            SELECT Field_Label__c, Field_API_Name__c, Data_Type__c
            FROM Product_Template_Name_Map__mdt
        ];
        for (Product_Template_Name_Map__mdt PTN : PTN_Mappings) {
            labelToApiName.put(PTN.Field_Label__c, PTN.Field_API_Name__c);
            labelToDataType.put(PTN.Field_Label__c, PTN.Data_Type__c);
        }

        List<OpportunityLineItem> requeriedOlis = requeryOlis(this.olis, fieldsInTemplate, labelToApiName);

        String fullCSVString = '';
        fullCsvString += generateHeaderRow(fieldsInTemplate);

        if (!requeriedOlis.isEmpty()) {
            fullCSVString += generateBodyRows(requeriedOlis, fieldsInTemplate, labelToApiName, labelToDataType);
        }
        return fullCSVString;
    }

    @TestVisible
    private String generateHeaderRow(List<Product_Template_Field__c> queryFields) {
        String headerLine = '';
        if (queryFields.size() > 0) {
            for (Integer i = 0; i < (queryFields.size() - 1); i++) {
                headerLine += queryFields[i].Field_Name__c + ', ';
            }
            headerLine += queryFields[queryFields.size() - 1].Field_Name__c + '\n';
        }

        return headerLine;
    }

    @TestVisible
    private String generateBodyRows(List<OpportunityLineItem> olis,
            List<Product_Template_Field__c> queryFields, Map<String, String> labelToApiName,
            Map<String, String> labelToDataType) {

        String vendorCSVString = '';

        for (OpportunityLineItem anOLI : olis) {  // for every OLI retrieved by the query

            String csvLine = '';
            for (Product_Template_Field__c aPTF : queryFields) {  // for every field selected
                // The 'get' function can only be used on OLI items.  The others must be hard-coded.
                String aString;
                String fieldApiName = labelToApiName.get(aPTF.Field_Name__c);
                // Need to treat Date fields, Decimal fields, and others separately to convert to a string.
                if (labelToDataType.get(aPTF.Field_Name__c) == 'Date') {
                    Date aDate;
                    DateTime aDateTime;
                    if (fieldApiName == 'ServiceDate') {
                        aDate = (Date) anOLI.ServiceDate;
                    } else if (fieldApiName == 'LastModifiedDate') {
                        aDateTime = (DateTime) anOLI.LastModifiedDate;
                        aDate = aDateTime.date();
                    } else if (fieldApiName == 'CreatedDate') {
                        aDateTime = (DateTime) anOLI.CreatedDate;
                        aDate = aDateTime.date();
                    } else if (fieldApiName == 'Opportunity.CloseDate') {
                        aDate = (Date) anOLI.Opportunity.CloseDate;
                    } else if (fieldApiName == 'Product2.Available_to_Ship_Date__c') {
                        aDate = (Date) anOLI.Product2.Available_to_Ship_Date__c;
                    }

                    if (aDate != null) {
                        aString = aDate.format();
                    }

                } else if (labelToDataType.get(aPTF.Field_Name__c) == 'Decimal') {
                    Decimal aDecimal;
                    if (fieldApiName == 'Quantity') {
                        aDecimal = (Decimal) anOLI.Quantity;
                    } else if (fieldApiName == 'Product2.Cost__c') {
                        aDecimal = (Decimal) anOLI.Product2.Cost__c;
                    }

                    if (aDecimal != null) {
                        aString = aDecimal.format();
                    }

                } else {
                    if (fieldApiName == 'Id' || fieldApiName == 'Name' ||
                            fieldApiName == 'ProductCode') {
                        // The 'get' function here can only be used on OLI fields, not parents.
                        aString = String.valueOf(anOLI.get(fieldApiName));
                    } else if (fieldApiName == 'Opportunity.Shipping_Street__c') {
                        aString = String.valueOf(anOLI.Opportunity.Shipping_Street__c);
                    } else if (fieldApiName == 'Opportunity.Shipping_City__c') {
                        aString = String.valueOf(anOLI.Opportunity.Shipping_City__c);
                    } else if (fieldApiName == 'Opportunity.Shipping_State__c') {
                        aString = String.valueOf(anOLI.Opportunity.Shipping_State__c);
                    } else if (fieldApiName == 'Opportunity.Shipping_Postal_Code__c') {
                        aString = String.valueOf(anOLI.Opportunity.Shipping_Postal_Code__c);
                    } else if (fieldApiName == 'Opportunity.Contact__r.FirstName') {
                        aString = String.valueOf(anOLI.Opportunity.Contact__r.FirstName);
                    } else if (fieldApiName == 'Opportunity.Contact__r.LastName') {
                        aString = String.valueOf(anOLI.Opportunity.Contact__r.LastName);
                    } else if (fieldApiName == 'Opportunity.Contact__r.Email') {
                        aString = String.valueOf(anOLI.Opportunity.Contact__r.Email);
                    } else if (fieldApiName == 'Product2.Id') {
                        aString = String.valueOf(anOLI.Product2.Id);
                    } else if (fieldApiName == 'Product2.Distributor__c') {
                        aString = String.valueOf(anOLI.Product2.Distributor__c);
                    } else if (fieldApiName == 'Product2.Estimated_Shipping_Time__c') {
                        aString = String.valueOf(anOLI.Product2.Estimated_Shipping_Time__c);
                    } else if (fieldApiName == 'Product2.Shipping_Method__c') {
                        aString = String.valueOf(anOLI.Product2.Shipping_Method__c);
                    } else if (fieldApiName == 'Product2.StockKeepingUnit') {
                        aString = String.valueOf(anOLI.Product2.StockKeepingUnit);
                    } else if (fieldApiName == 'Product2.ProductCode') {
                        aString = String.valueOf(anOLI.Product2.ProductCode);
                    } else if (fieldApiName == 'Product2.Type__c') {
                        aString = String.valueOf(anOLI.Product2.Type__c);
                    } else if (fieldApiName == 'Opportunity.Id') {
                        aString = String.valueOf(anOLI.Opportunity.Id);
                    } else if (fieldApiName == 'Opportunity.Account.AccountNumber') {
                        aString = String.valueOf(anOLI.Opportunity.Account.AccountNumber);
                    }

                }

                if (aString != null) {
                    aString = aString.replace(',', ':'); // Must not have commas going into a CSV file.
                } else {
                    aString = '';  // Otherwise 'null' shows up in the output.
                }
                csvLine += aString + ', ';
            }   // for (Product_Template_Field__c aPTF : queryFields)

            if (csvLine.length() > 2) {
                csvLine = csvLine.substring(0, (csvLine.length() - 2));  // Get rid of last comma
            }

            csvLine += '\n';

            vendorCSVString += csvLine;
        } // for (OpportunityLineItem anOLI : queryResultSet)

        return vendorCSVString;

    }
}