force-app/main/default/objects/Account/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Product Order Template: The preferred format for order exports generated for this vendor</inlineHelpText>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Order__c/Batch_Order__c.object-meta.xml
<CustomObject>
    <label>Batch Order</label>
    <nameField>
        <displayFormat>BO-{0000}</displayFormat>
        <label>Batch Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem/fields/Batch_Order__c.field-meta.xml
<CustomField>
    <fullName>Batch_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The order export in which this gift can be found (if blank, fulfillment has not begun)</inlineHelpText>
    <label>Batch Order</label>
    <referenceTo>Batch_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Order_Template__c/Product_Order_Template__c.object-meta.xml
<CustomObject>
    <description>A list of data elements associated with a product order.  The product order itself is an Opportunity Line Item record that is associated with an Opportunity, a Contact, and a Product (Product2) record.</description>
    <label>Product Order Template</label>
    <nameField>
        <label>Product Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/Product_Template_Field__c.object-meta.xml
<CustomObject>
    <description>This represents the selection of a field on either the Product (Product2), Opportunity Line Item, Opportunity, or Contact object.</description>
    <label>Product Template Field</label>
    <nameField>
        <displayFormat>PTF-{000000}</displayFormat>
        <label>Product Template Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>This is the list of the fields that one can pick from in order to create a template.

NOTE: The picklist values in this field must be kept in sync with the Field Name values in the custom metadata type named Product Template Name Map.</description>
    <label>Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opp Product: Id</fullName>
            </value>
            <value>
                <fullName>Opp Product: Name</fullName>
            </value>
            <value>
                <fullName>Opp Product: ProductCode</fullName>
            </value>
            <value>
                <fullName>Opp Product: Quantity</fullName>
            </value>
            <value>
                <fullName>Opp Product: Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Created Date</fullName>
            </value>
            <value>
                <fullName>Opp Product: Last Mod Date</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Street</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping City</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping State</fullName>
            </value>
            <value>
                <fullName>Opportunity: Shipping Postal Code</fullName>
            </value>
            <value>
                <fullName>Contact: First Name</fullName>
            </value>
            <value>
                <fullName>Contact: Last Name</fullName>
            </value>
            <value>
                <fullName>Contact: Email</fullName>
            </value>
            <value>
                <fullName>Product: Id</fullName>
            </value>
            <value>
                <fullName>Product: Available To Ship Date</fullName>
            </value>
            <value>
                <fullName>Product: Cost</fullName>
            </value>
            <value>
                <fullName>Product: Distributor</fullName>
            </value>
            <value>
                <fullName>Product: Estimated Ship Time</fullName>
            </value>
            <value>
                <fullName>Product: Generic Product</fullName>
            </value>
            <value>
                <fullName>Product: Product Code</fullName>
            </value>
            <value>
                <fullName>Product: Stock Keeping Unit</fullName>
            </value>
            <value>
                <fullName>Product: Shipping Method</fullName>
            </value>
            <value>
                <fullName>Product: Type</fullName>
            </value>
            <value>
                <fullName>Opportunity: Id</fullName>
            </value>
            <value>
                <fullName>Opportunity: Account Number</fullName>
            </value>
            <value>
                <fullName>Opportunity: Close Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <description>Determines the placement of this field within the Product Order Template.</description>
    <inlineHelpText>Index of field column when exported to Excel</inlineHelpText>
    <label>Field Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Template_Field__c/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <description>Determines the template that this particular field is associated with.</description>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Product Template Fields</relationshipLabel>
    <relationshipName>Product_Template_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchOrderCreationControllerTest.cls
@IsTest
public with sharing class BatchOrderCreationControllerTest {

    @testSetup
    static void testSetup() {
        Product_Order_Template__c template1 = new Product_Order_Template__c(Name = 'Template 1',
            Active__c = true);
        insert template1;

        Product_Template_Field__c template1PTF1 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Id',
                Field_Order__c = 1, Product_Order_Template__c = template1.Id);
        Product_Template_Field__c template1PTF2 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Name',
                Field_Order__c = 2, Product_Order_Template__c = template1.Id);
        Product_Template_Field__c template1PTF3 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: ProductCode',
                Field_Order__c = 3, Product_Order_Template__c = template1.Id);
        Product_Template_Field__c template1PTF4 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Quantity',
                Field_Order__c = 4, Product_Order_Template__c = template1.Id);
        Product_Template_Field__c template1PTF5 = new Product_Template_Field__c(Field_Name__c = 'Opp Product: Date',
                Field_Order__c = 5, Product_Order_Template__c = template1.Id);
        insert new List<Product_Template_Field__c>{
            template1PTF1, template1PTF2, template1PTF3, template1PTF4, template1PTF5
        };

        List<Account> vendorAccount1 = TestUtilities.createVendors(1, true);
        List<Account> vendorAccount2 = TestUtilities.createVendors(1, true);
        List<Account> nonVendorAccount = TestUtilities.createAccounts(1, true);

        vendorAccount1[0].Name = 'Vendor 1';
        vendorAccount1[0].Product_Order_Template__c = template1.Id;
        vendorAccount2[0].Name = 'Vendor 2';
        vendorAccount2[0].Product_Order_Template__c = template1.Id;
        nonVendorAccount[0].Name = 'Non Vendor';

        List<Account> theAccounts = new List<Account>{vendorAccount1[0], vendorAccount2[0], nonVendorAccount[0]};
        update theAccounts;

        List<Account> customerAccount = TestUtilities.createAccounts(1, true);
        List<Contact> customerContact = TestUtilities.createContacts(customerAccount);
        List<Opportunity> customerOpportunities = TestUtilities.createOpportunities(customerAccount, 1, true);

        List<Product2> vendorProduct1 = TestUtilities.createProducts(1, vendorAccount1[0].Id, true);

        Pricebook2 pb = TestUtilities.createPricebook('pb', true);
        customerOpportunities[0].Pricebook2Id = pb.Id;
        update customerOpportunities[0];

        List<PricebookEntry> pbEntries1 = TestUtilities.createPricebookEntries(vendorProduct1, pb.Id, true);

        List<OpportunityLineItem> newOLIs = TestUtilities.createOpportunityLineItems(customerOpportunities, pbEntries1, 1, true);
        List<OpportunityLineItem> generatedOLIs = TestUtilities.createOpportunityLineItems(customerOpportunities, pbEntries1, 1, true);

        for (OpportunityLineItem oli : newOLIs) {
            oli.Order_Status__c = 'New';
        }
        update newOLIs;

        for (OpportunityLineItem oli : newOLIs) {
            oli.Order_Status__c = 'Generated';
        }
        update generatedOLIs;
    }

    static testMethod void testGetProductTemplateId_Good() {
        Account theVendor = [SELECT Id FROM Account WHERE Name = 'Vendor 1'];

        Test.startTest();
            Id templateId = BatchOrderCreationController.getProductTemplateId(theVendor.Id);
        Test.stopTest();

        System.assertNotEquals(null, templateId, 'Should return a non-null template Id');
    }

    static testMethod void testGetProductTemplateId_Bad() {
        Account theVendor = [SELECT Id FROM Account WHERE Name = 'Non Vendor'];

        Test.startTest();
            Id templateId = BatchOrderCreationController.getProductTemplateId(theVendor.Id);
        Test.stopTest();

        System.assertEquals(null, templateId, 'Should return a null value');
    }

    static testMethod void checkForNewOpportunityProducts_Good() {
        Account theVendor = [SELECT Id FROM Account WHERE Name = 'Vendor 1'];

        Test.startTest();
            Boolean hasNewOLIs = BatchOrderCreationController.checkForNewOpportunityProducts(theVendor.Id);
        Test.stopTest();

        System.assert(hasNewOLIs, 'Should report that -New- OLIs do exist for this vendor.');
    }

    static testMethod void checkForNewOpportunityProducts_Bad() {
        Account theVendor = [SELECT Id FROM Account WHERE Name = 'Vendor 2'];

        Test.startTest();
            Boolean hasNewOLIs = BatchOrderCreationController.checkForNewOpportunityProducts(theVendor.Id);
        Test.stopTest();

        System.assert(!hasNewOLIs, 'Should report that NO -New- OLIs do exist for this vendor.');
    }

    static testMethod void testCreateBatchOrder() {
        Account theVendor = [SELECT Id FROM Account WHERE Name = 'Vendor 1'];
        Product_Order_Template__c theTemplate = [SELECT Id FROM Product_Order_Template__c WHERE Name = 'Template 1'];

        Test.startTest();
            BatchOrderCreationController.createBatchOrder(theVendor.Id, theTemplate.Id);
        Test.stopTest();

        List<ContentDocument> newContentDocuments = new List<ContentDocument>([SELECT Id from ContentDocument]);
        System.assertEquals(1, newContentDocuments.size(), 'There should one new Content Document.');

        List<Batch_Order__c> newBatchOrders = new List<Batch_Order__c>([SELECT Id from Batch_Order__c]);
        System.assertEquals(1, newBatchOrders.size(), 'There should one new Batch Order.');

        List<OpportunityLineItem> updatedOLIs = new List<OpportunityLineItem>([SELECT Id, Order_Status__c from OpportunityLineItem
                WHERE Order_Status__c = 'Generated']);
        System.assertEquals(2, updatedOLIs.size(), 'Two OLIs should now have a status of -Generated-.');  // One 'generated' OLI created for testing
    }
}