force-app/main/default/objects/Account/fields/Product_Order_Template__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Product Order Template: The preferred format for order exports generated for this vendor</inlineHelpText>
    <label>Product Order Template</label>
    <referenceTo>Product_Order_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent to Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Order_Template__c/Product_Order_Template__c.object-meta.xml
<CustomObject>
    <description>A list of data elements associated with a product order.  The product order itself is an Opportunity Line Item record that is associated with an Opportunity, a Contact, and a Product (Product2) record.</description>
    <label>Product Order Template</label>
    <nameField>
        <label>Product Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchOrderCreationController.cls
public with sharing class BatchOrderCreationController {

    @AuraEnabled
    public static Id getProductTemplateId(Id vendorId) {
        try {
            Account vendorAcct = [SELECT Id, Product_Order_Template__c FROM Account
                                        WHERE Id =: vendorId];
            if (vendorAcct.Product_Order_Template__c != null) {
                return vendorAcct.Product_Order_Template__c;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return null;
    }

    @AuraEnabled
    public static Boolean checkForNewOpportunityProducts(Id vendorId) {
        List<OpportunityLineItem> newOLIs = new List<OpportunityLineItem>();
        try {
            newOLIs = [SELECT Id FROM OpportunityLineItem WHERE Product2.Vendor__c = :vendorId AND Order_Status__c = 'New'];
            if (newOLIs.size() > 0) {
                return true;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return false;
    }

    @AuraEnabled
    public static void createBatchOrder(Id vendorId, Id templateId) {
        BatchOrderGenerator generator = new BatchOrderGenerator(vendorId, templateId); 
        generator.generateBatchOrders();
    }
}