force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact responsible for this donation, if applicable</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Tier__c.field-meta.xml
<CustomField>
    <fullName>Membership_Tier__c</fullName>
    <label>Membership Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MembershipUtilities.cls
public class MembershipUtilities {
    // TO DO - These two lines should be removed in MER-756.
    public static final String MEMBERSHIP_TIER_BASIC = 'Basic';
    public static final String MEMBERSHIP_TIER_LEADERSHIP = 'Leadership';
    public static final String CONTACT_MEMBERSHIP_TIER_NONE = 'None';
    public static final String CONTACT_MEMBERSHIP_TIER_BASIC = 'Basic';
    public static final String CONTACT_MEMBERSHIP_TIER_LEADERSHIP = 'Leadership';
    public static final String ACCOUNT_MEMBERSHIP_TIER_NONE = 'None';
    public static final String ACCOUNT_MEMBERSHIP_TIER_BASIC = 'Basic';
    public static final String ACCOUNT_MEMBERSHIP_TIER_LEADERSHIP = 'Leadership';

    public static final Decimal MINIMUM_OT_LEADERSHIP = 150;
    public static final Decimal MINIMUM_SG_LEADERSHIP = 12.5;

    public static final String END_REASON_ONE_TIME_DEFAULT = 'End of Life';
    public static final String END_REASON_SUSTAINER_DEFAULT = 'Nonpayment';
    public static final String END_REASON_CANCELLED = 'Cancelled';

    public static Opportunity expireOpportunityMembership(Opportunity theOpp) {
        theOpp.Membership_Active__c = false;
        if (theOpp.End_Reason__c == null) {
            theOpp.End_Reason__c = theOpp.Is_Monthly__c ? END_REASON_SUSTAINER_DEFAULT : END_REASON_ONE_TIME_DEFAULT;
        }
        return theOpp;
    }

    public static Map<Id, String> getNewMembershipTiersByContact(Set <Id> contactIdsToRecalculate) {

        Map<Id, String> contactTiers = new Map<Id, String>();
        
        List<Opportunity> allRelatedOpportunities = new List<Opportunity>([SELECT Id, Membership_Tier__c, Contact__c
                FROM Opportunity WHERE Contact__c in :contactIdsToRecalculate AND Membership_Active__c = TRUE]);

        // Start by assuming all Contacts have no opportunities at all
        for (Id theContactId : contactIdsToRecalculate) {
            contactTiers.put(theContactId, MembershipUtilities.CONTACT_MEMBERSHIP_TIER_NONE);
        }

        Map<String,List<Opportunity>> relatedOppsByTier = GroupBy.strings('Membership_Tier__c', allRelatedOpportunities);
        if (relatedOppsByTier.containsKey(MembershipUtilities.CONTACT_MEMBERSHIP_TIER_BASIC)) {
            for (Opportunity anOpp : relatedOppsByTier.get(MembershipUtilities.MEMBERSHIP_TIER_BASIC)) {
                contactTiers.put(anOpp.Contact__c, MembershipUtilities.CONTACT_MEMBERSHIP_TIER_BASIC);
            }
        }
        if (relatedOppsByTier.containsKey(MembershipUtilities.CONTACT_MEMBERSHIP_TIER_LEADERSHIP)) {
            for (Opportunity anOpp : relatedOppsByTier.get(MembershipUtilities.MEMBERSHIP_TIER_LEADERSHIP)) {
                contactTiers.put(anOpp.Contact__c, MembershipUtilities.CONTACT_MEMBERSHIP_TIER_LEADERSHIP);
            }
        }

        return contactTiers;

    }
}