force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, Opportunity was cancelled manually at donor&#39;s request</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Worldpay_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Order_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Worldpay unique identifier</inlineHelpText>
    <label>Worldpay Order Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityServicesTest.cls
@IsTest
public class OpportunityServicesTest {
    //TODO: FIX THIS TESTMETHOD
    public static testMethod void testCancelMembership() {
        Contact testContact = TestUtilities.createContacts(1, true)[0];
        testContact = [SELECT Id, AccountId FROM Contact WHERE Id = :testContact.Id];
        Opportunity testOpp = TestUtilities.createOpportunities(new List<Contact>{testContact}, 1, true)[0];
        Payment__c completedPayment = TestUtilities.createPayment(testOpp, false);
        Payment__c pendingPayment = TestUtilities.createPayment(testOpp, false);
        completedPayment.Status__c = PaymentServices.APPROVED_STATUS;
        completedPayment.Worldpay_Order_Id__c = 'uniquevalue0';
        List<Payment__c> allPayments = new List<Payment__c>{completedPayment, pendingPayment};
        insert allPayments;

        Test.startTest();
            Opportunity returnedOpp = OpportunityServices.cancelDonation(testOpp);
        Test.stopTest();

        List<Payment__c> requeriedPayments = [SELECT Status__c FROM Payment__c WHERE Id IN :allPayments];
        
        System.assert(returnedOpp.Is_Cancelled__c, 'Expect the returned opportunity to have been cancelled');
        System.assertEquals(MembershipUtilities.END_REASON_CANCELLED, returnedOpp.End_Reason__c, 'Expect cancelled donations end reason to reflect that it was cancelled');
        System.assertEquals(allPayments.size(), requeriedPayments.size(), 'No payments should have been deleted');
        for (Payment__c aPayment : requeriedPayments) {
            if (aPayment.Id == completedPayment.Id) {
                System.assertEquals(PaymentServices.APPROVED_STATUS, aPayment.Status__c, 'Expect non-pending payments to not have their status updated');
            }
            else {
                System.assertEquals(PaymentServices.CANCELLED_STATUS, aPayment.Status__c, 'Expect pending payments to have their status updated from pending to cancelled');
            }
        }
    }
}