force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_End_Date__c</fullName>
    <description>Monthly: End of the month following the most recent payment. One Time:  End of month following 12 months from Oppty close date.</description>
    <inlineHelpText>Date membership benefits for this donation are projected to expire if subsequent payment is not processed</inlineHelpText>
    <label>Projected End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MembershipExpirationBatch.cls
global class MembershipExpirationBatch implements Database.Batchable<sObject>, Database.Stateful{
    @TestVisible List<String> failedMembershipReasons = new List<String>();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Is_Monthly__c, Projected_End_Date__c,  End_Reason__c FROM Opportunity WHERE '
                      +'Projected_End_Date__c <= TODAY AND '
                      +'Membership_Active__c = true';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        for (Opportunity anOpp : scope) {
            MembershipUtilities.expireOpportunityMembership(anOpp);
        }
        List<Database.SaveResult> sr = Database.update(scope, false);
        for (Database.SaveResult aSaveResult : sr) {
            if (!aSaveResult.isSuccess()) {
                for (Database.Error err : aSaveResult.getErrors()) {
                    failedMembershipReasons.add(aSaveResult.getId() + '; ' + err.getMessage());
                }
            }
        }
    }

    global void finish(Database.BatchableContext bc) {
        if (!failedMembershipReasons.isEmpty()) {
            String failedMembershipReasonsString = String.join(failedMembershipReasons, '\n');

            ErrorLog.logError(null, 'MembershipExpirationBatch', failedMembershipReasonsString);
            ErrorLog.commitErrors();
        }
    }

}