force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, Opportunity was cancelled manually at donor&#39;s request</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Original_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Payment_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If record is a refund, the approved payment that was refunded</inlineHelpText>
    <label>Original Payment Id</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityServices.cls
public class OpportunityServices {
    
    public static final INTEGER DAYS_TO_QUERY = 365;
    
    public static Opportunity cancelDonation(Opportunity opp) {
        opp = [SELECT Id,
                    (SELECT Id FROM Payments__r WHERE Status__c = :PaymentServices.PENDING_STATUS)
                FROM Opportunity
                WHERE Id = :opp.Id];
        for (Payment__c aPayment : opp.Payments__r) {
            aPayment.Status__c = PaymentServices.CANCELLED_STATUS;
        }
        opp.End_Reason__c = MembershipUtilities.END_REASON_CANCELLED;
        opp.Is_Cancelled__c = true;
        Savepoint sp = Database.setSavepoint();
        try {
            if (!opp.Payments__r.isEmpty()) update opp.Payments__r;
            update opp;
        }
        catch (DMLException e) {
            Database.rollback(sp);
            throw new AuraHandledException(e.getDmlMessage(0));
        }
        return opp;
    }
}