force-app/main/default/objects/Contact/fields/Membership_Tier__c.field-meta.xml
<CustomField>
    <fullName>Membership_Tier__c</fullName>
    <label>Membership Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End of Life</fullName>
            </value>
            <value>
                <fullName>Nonpayment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, Opportunity was cancelled manually at donor&#39;s request</inlineHelpText>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Tier__c.field-meta.xml
<CustomField>
    <fullName>Membership_Tier__c</fullName>
    <label>Membership Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Leadership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Original_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Payment_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If record is a refund, the approved payment that was refunded</inlineHelpText>
    <label>Original Payment Id</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonationCancelControllerTest.cls
@IsTest
public with sharing class DonationCancelControllerTest {
    
    public static testMethod void testCancelDonation() {
        List<Contact> testContact = TestUtilities.createContacts(1, true);
        testContact = [SELECT Id, AccountId FROM Contact WHERE Id = :testContact];
        Opportunity testOpp = TestUtilities.createOpportunities(testContact, 1, false)[0];
        testOpp.End_Reason__c = null;
        testOpp.Membership_Active__c = true;
        testOpp.Membership_Tier__c = MembershipUtilities.MEMBERSHIP_TIER_BASIC;
        insert testOpp;
        Payment__c processedPayment = TestUtilities.createPayment(testOpp, false);
        processedPayment.Status__c = PaymentServices.APPROVED_STATUS;
        Payment__c pendingPayment = TestUtilities.createPayment(testOpp, false);
        Test.startTest();
            DonationCancelController.cancelDonation(new Opportunity(Id = testOpp.Id));
        Test.stopTest();

        Opportunity requeriedOpp = [SELECT Id, End_Reason__c, Is_Cancelled__c,
                                        (SELECT Id, Status__c FROM Payments__r)
                                    FROM Opportunity WHERE Id = :testOpp.Id];
        System.assert(requeriedOpp.Is_Cancelled__c, 'Expect the opportunity to be cancelled');
        System.assertEquals(MembershipUtilities.END_REASON_CANCELLED, requeriedOpp.End_Reason__c, 'Expect the end reason to be set to cancelled');
        for (Payment__c aPayment : requeriedOpp.Payments__r) {
            if (aPayment.Id == processedPayment.Id) {
                System.assertEquals(processedPayment.Status__c, aPayment.Status__c, 'Expect the status of a non-pending payment to remain unchanged');
            }
            else {
                System.assertEquals(PaymentServices.CANCELLED_STATUS, aPayment.Status__c, 'Expect the status of a pending payment to change to cancelled');
            }
        }
    }

    public static testMethod void testGetDonation() {
        List<Contact> testContact = TestUtilities.createContacts(1, true);
        testContact = [SELECT Id, AccountId FROM Contact WHERE Id = :testContact];
        Opportunity testOpp = TestUtilities.createOpportunities(testContact, 1, false)[0];
        insert testOpp;

        Test.startTest();
            DonationCancelController.getDonation(testOpp.Id);
        Test.stopTest();

        Opportunity requeriedOpp = [SELECT Id, End_Reason__c, Is_Cancelled__c
                                    FROM Opportunity WHERE Id = :testOpp.Id];

        System.assertNotEquals(null, requeriedOpp.Id, 'Opp Id should not be null.');
        System.assert(!requeriedOpp.Is_Cancelled__c, 'Expect the opportunity to not be cancelled');
    }
    
}