force-app/main/default/objects/Contact/fields/Membership_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Membership_Benefits__c</fullName>
    <label>Membership Benefits</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_Inactive_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Inactive_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all donations from inactive sustaining donations in the last year</inlineHelpText>
    <label>Sum Inactive Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_One_Time_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_One_Time_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all of the one time donations from this Contact within the last year</inlineHelpText>
    <label>Sum One Time Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Annualized_Donation_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Annualized_Donation_Value__c</fullName>
    <formula>Sum_One_Time_Last_Year_Donations__c +   Sum_Annualized_Sustaining_Donations__c + Sum_Inactive_Last_Year_Donations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The sum total of all donations from this Contact in the last year</inlineHelpText>
    <label>Total Annualized Donation Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <label>Member Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/Member_Benefit_Level__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Level</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>Member Level Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefit Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Level__c.field-meta.xml
<CustomField>
    <fullName>Member_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Level</label>
    <referenceTo>Member_Level__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Level__c/Member_Level__c.object-meta.xml
<CustomObject>
    <label>Member Level</label>
    <nameField>
        <label>Member Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Level__c/fields/Member_Level_Value__c.field-meta.xml
<CustomField>
    <fullName>Member_Level_Value__c</fullName>
    <inlineHelpText>The amount of annual donations needed to be considered for this level.  The donations consist of monthly giving (annualized) and one time donations within the last year.</inlineHelpText>
    <label>Member Level Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Amount__c</fullName>
    <label>Initial Payment Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <inlineHelpText>Date a payment was processed by Worldpay (if blank, transaction has not yet occurred)</inlineHelpText>
    <label>Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactUtilitiesTest.cls
@IsTest
public with sharing class ContactUtilitiesTest {
 
    @testSetup static void setup() {

        Member_Benefit__c mb1 = new Member_Benefit__c (Name = 'Benefit 1', Description__c = 'Benefit 1');
        Member_Benefit__c mb2 = new Member_Benefit__c (Name = 'Benefit 2', Description__c = 'Benefit 2');
        insert new List<Member_Benefit__c>{mb1, mb2};            
        
        Member_Level__c ml1 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 100);
        Member_Level__c ml2 = new Member_Level__c (Name = 'Level 1', Member_Level_Value__c = 200);
        insert new List<Member_Level__c>{ml1, ml2};            
        
        Member_Benefit_Level__c mbl1 = new Member_Benefit_Level__c(Member_Benefit__c = mb1.Id, Member_Level__c = ml1.Id);
        Member_Benefit_Level__c mbl2 = new Member_Benefit_Level__c(Member_Benefit__c = mb2.Id, Member_Level__c = ml2.Id);
        insert new List<Member_Benefit_Level__c>{mbl1, mbl2};   

    }
    
    static testMethod void testMemberLevelString_1() {
        
        List<Account> accounts = TestUtilities.createAccounts(1, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        contacts[0].Sum_Annualized_Sustaining_Donations__c = 75;

        Test.startTest();
            update contacts;
        Test.stopTest();

        List<Contact> updatedContacts1 = [SELECT Id, Membership_Benefits__c FROM Contact];
        for (Contact c : updatedContacts1) {
            System.assertEquals(null, c.Membership_Benefits__c, 'Value should be null.');
        }        
 
    }

    static testMethod void testMemberLevelString_2() {

        List<Account> accounts = TestUtilities.createAccounts(1, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        contacts[0].Sum_Annualized_Sustaining_Donations__c = 150;

        Test.startTest();
            update contacts;
        Test.stopTest();

        List<Contact> updatedContacts2 = [SELECT Id, Membership_Benefits__c FROM Contact];
        for (Contact c : updatedContacts2) {
            System.assertEquals('Benefit 1', c.Membership_Benefits__c, 'Value should be \'Benefit 1\'.');
        }
 
    }

    static testMethod void testMemberLevelString_3() {

        List<Account> accounts = TestUtilities.createAccounts(1, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        contacts[0].Sum_Annualized_Sustaining_Donations__c = 225;
        
        Test.startTest();
            update contacts;
        Test.stopTest();

        List<Contact> updatedContacts3 = [SELECT Id, Membership_Benefits__c FROM Contact];
        for (Contact c : updatedContacts3) {
            System.assertEquals('Benefit 2', c.Membership_Benefits__c, 'Value should be \'Benefit 2\'.');
        }        
 
    }
   
    static testMethod void testRecalcValues() {
        
        List<Account> accounts = TestUtilities.createAccounts(1, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);
        
        // Opp 0 will be a one time donation of $100
        // Opp 1 will be an active recurring donation of $15 monthly ($180 annualized)
        // Opp 2 will be an inactive recurring donation with one $50 payment
        // Opp 3 has a Cancelled payment which should not be counted.
        // Opp 4 has a 15 month old payment that should not be counted.
        
        List<Opportunity> opps = TestUtilities.createOpportunities(contacts, 5, false);
        for (Opportunity opp : opps ) {
          opp.Membership_Active__c = true;
          opp.CloseDate = Date.today().addMonths(-2);
        }
        opps[0].Is_Monthly__c = false;
        opps[1].Is_Monthly__c = true;
        opps[2].Is_Monthly__c = true;
        opps[2].Membership_Active__c = false;
        opps[3].Is_Monthly__c = false;
        opps[4].Is_Monthly__c = false;
        opps[4].CloseDate = Date.today().addMonths(-15);

        opps[0].Initial_Payment_Amount__c = 100;
        opps[1].Initial_Payment_Amount__c = 15;
        opps[2].Initial_Payment_Amount__c = 50;        
        opps[3].Initial_Payment_Amount__c = 200;
        opps[4].Initial_Payment_Amount__c = 75;
        insert opps;

        List<Payment__c> payments = TestUtilities.createPayments(opps, false);
        for (Payment__c payment : payments ) {
          payment.Status__c = PaymentServices.APPROVED_STATUS;
          payment.Post_Date__c = Date.today().addMonths(-2);
        }
        payments[0].Amount__c = 100;
        payments[1].Amount__c = 15;
        payments[2].Amount__c = 50;
        payments[3].Amount__c = 200;
        payments[4].Amount__c = 75;
        payments[3].Status__c = PaymentServices.CANCELLED_STATUS;
        payments[4].Post_Date__c = Date.today().addMonths(-15);
        insert payments;

        Test.startTest();
            ContactUtilities.recalcAnnualDonationValues(opps);
        Test.stopTest();

        List<Contact> updatedContacts = [SELECT Id, Sum_One_Time_Last_Year_Donations__c, 
            Sum_Annualized_Sustaining_Donations__c, Sum_Inactive_Last_Year_Donations__c,
            Total_Annualized_Donation_Value__c
            FROM Contact];

        for (Contact c : updatedContacts) {
            System.assertEquals(330, c.Total_Annualized_Donation_Value__c, 'Value should be 330'); // 100 + 180 + 50
        }

    } 

}