force-app/main/default/objects/Contact/fields/Possible_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Possible_Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this Contact may have duplicate Contacts in the database that should be reviewed.</description>
    <inlineHelpText>Identifies new donor as a potential duplicate of a Contact already in the system</inlineHelpText>
    <label>Possible Duplicate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Match_Threshold__c/Contact_Match_Threshold__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Contact Match Threshold</label>
</CustomObject>

force-app/main/default/objects/Contact_Match_Threshold__c/fields/Min_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Min_Threshold__c</fullName>
    <label>Min Threshold</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactMatch.cls
public without sharing class ContactMatch {
    
    public static Contact getUniqueContact(Contact theContact) {
        Datacloud.MatchRecord highestMatchingContact = getHighestMatchRecord(theContact);
        if (highestMatchingContact == null) {
            System.debug('NO DUPLICATE EXISTS!');
        }
        else {
            System.debug('CONFIDENCE SCORE: ' + highestMatchingContact.getMatchConfidence());
            Decimal threshold = Contact_Match_Threshold__c.getInstance().Min_Threshold__c;
            if (threshold == null) threshold = 95;
            if (highestMatchingContact.getMatchConfidence() >= threshold) {  // Using duplicate contact, NOT creating a new one
                Id matchId = highestMatchingContact.getRecord().Id;
                theContact.Id = matchId;
            } else {  // A potential duplicate exists but the score is below the threshold.  New contact will be created.
                theContact.Possible_Duplicate__c = true;
            } 
        }
        return theContact;
    }

    private static Datacloud.MatchRecord getHighestMatchRecord(Contact theContact) {
        Datacloud.MatchRecord highestRecord;
        List<Datacloud.FindDuplicatesResult> findDuplicateResults = Datacloud.FindDuplicates.findDuplicates(new List<Contact>{theContact});
        List<Datacloud.DuplicateResult> duplicateResults = findDuplicateResults[0].duplicateresults;
        for (Datacloud.DuplicateResult dr : duplicateResults) {
            List<Datacloud.MatchResult> matchResults = dr.getMatchResults(); // unlikely to ever be more than 2 matchResults per duplicateResult
            if (matchResults != null && !matchResults.isEmpty()) {
                for (Datacloud.MatchResult mResult : matchResults) {
                    List<Datacloud.MatchRecord> matchRecords = mResult.getMatchRecords();
                    if (matchRecords != null && !matchRecords.isEmpty()) {
                        for (Datacloud.MatchRecord mRecord : matchRecords) {
                            if ((highestRecord == null || mRecord.getMatchConfidence() > highestRecord.getMatchConfidence()) && (mRecord.getRecord() instanceof Contact)) {
                                highestRecord = mRecord;
                            }
                        }
                    }
                }
            }
        }
        return highestRecord;
    }

}