force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_Inactive_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Inactive_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all donations from inactive sustaining donations in the last year</inlineHelpText>
    <label>Sum Inactive Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_One_Time_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_One_Time_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all of the one time donations from this Contact within the last year</inlineHelpText>
    <label>Sum One Time Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ZeroOutAnnualContactFieldsBatch.cls
global class ZeroOutAnnualContactFieldsBatch implements Database.Batchable<sObject> {
	
    global Database.QueryLocator start(Database.BatchableContext BC) {
      
        String query = 'SELECT Id, Sum_One_Time_Last_Year_Donations__c, Sum_Annualized_Sustaining_Donations__c,'
                                + ' Sum_Inactive_Last_Year_Donations__c'
                        		+ ' FROM Contact';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope){
        
        List<Contact> contactsToUpdate = new List<Contact>();

        for (Contact c : scope) {
            c.Sum_One_Time_Last_Year_Donations__c = null;
            c.Sum_Annualized_Sustaining_Donations__c = null;
            c.Sum_Inactive_Last_Year_Donations__c = null;
            contactsToUpdate.add(c);
        }   
  
        try {
            update contactsToUpdate;
        } catch (DMLException ex) {
            ErrorLog.logError(ex, 'ZeroOutAnnualContactFields', 'Error updating Contact values.');
            ErrorLog.commitErrors();
        }    

    }  

    global void finish(Database.BatchableContext bc) {
        CalcPaymentTotalBatch batch = new CalcPaymentTotalBatch();
        database.executebatch(batch);
    }

}