force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_Inactive_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Inactive_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all donations from inactive sustaining donations in the last year</inlineHelpText>
    <label>Sum Inactive Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_One_Time_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_One_Time_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all of the one time donations from this Contact within the last year</inlineHelpText>
    <label>Sum One Time Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Member_Benefit__c/Member_Benefit__c.object-meta.xml
<CustomObject>
    <label>Member Benefit</label>
    <nameField>
        <label>Member Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/Member_Benefit_Level__c.object-meta.xml
<CustomObject>
    <label>Member Benefit Level</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>Member Level Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Benefit Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Member_Benefit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Benefit</label>
    <referenceTo>Member_Benefit__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Benefit_Level__c/fields/Member_Level__c.field-meta.xml
<CustomField>
    <fullName>Member_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member Level</label>
    <referenceTo>Member_Level__c</referenceTo>
    <relationshipLabel>Member Benefit Levels</relationshipLabel>
    <relationshipName>Member_Benefit_Levels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Level__c/Member_Level__c.object-meta.xml
<CustomObject>
    <label>Member Level</label>
    <nameField>
        <label>Member Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Level__c/fields/Member_Level_Value__c.field-meta.xml
<CustomField>
    <fullName>Member_Level_Value__c</fullName>
    <inlineHelpText>The amount of annual donations needed to be considered for this level.  The donations consist of monthly giving (annualized) and one time donations within the last year.</inlineHelpText>
    <label>Member Level Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact responsible for this donation, if applicable</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Amount__c</fullName>
    <label>Initial Payment Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <inlineHelpText>Date a payment was processed by Worldpay (if blank, transaction has not yet occurred)</inlineHelpText>
    <label>Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactUtilities.cls
public with sharing class ContactUtilities {

    // Creates a map of the various member levels and strings that contains all of the benefits for that member level.
    public static Map<Member_Level__c, String> getMemberBenefitStrings() { 

        List <Member_Level__c> memberLevels = new List<Member_Level__c>([SELECT Name, Member_Level_Value__c 
                FROM Member_Level__c ORDER BY Member_Level_Value__c DESC]);

        List <Member_Benefit_Level__c> memberBenefitLevels = new List<Member_Benefit_Level__c>([SELECT Member_Benefit__c,
                Member_Level__c, Member_Level__r.Name, Member_Benefit__r.Name FROM Member_Benefit_Level__c ]);

        Map<Member_Level__c, String> memberLevelBenefits = new Map<Member_Level__c, String>();

        for (Member_Level__c memberLevel : memberLevels) {
            String benefitString = '';
            for (Member_Benefit_Level__c mbl : memberBenefitLevels) {
                if (memberLevel.Id == mbl.Member_Level__c) {
                    benefitString += mbl.Member_Benefit__r.Name + ', ';
                }
            }
            if (benefitString.contains(', ')) {
                benefitString = benefitString.substring(0, benefitString.length()-2);
            }        
            memberLevelBenefits.put(memberLevel, benefitString);
        }

        return memberLevelBenefits;
    }

    // This function mimics the four batch files that are used to calculate the annual donation values.
    // It is called upon updates to Opportunities that could result in the Contact's values changing.
    // There were too many possible Opportunity updates (i.e. refund, change in payment amount or Contact, 
    // deletion) to handle them individually.  Instead, this method recalcs all of the values from scratch.
    public static void recalcAnnualDonationValues(List<Opportunity> updatedOpps) {

        // Start by taking the updated Opportunities, getting the associated Contacts,
        // and then getting all of the Opportunities related to these Contacts.
        Set<Id> contactIds = new Set<Id>();
        for (Opportunity anOpp : updatedOpps) {
            if (anOpp.Contact__c != null) {
                contactIds.add(anOpp.Contact__c);
            }
        }

        Map<Id, Contact> relatedContacts = new Map<Id, Contact>([SELECT Id, Sum_One_Time_Last_Year_Donations__c, 
                Sum_Annualized_Sustaining_Donations__c, Sum_Inactive_Last_Year_Donations__c
                FROM Contact WHERE Id IN :contactIds]);

        // Need all of the Opportunities associated with all of the related Contacts
        List<Opportunity> relatedOpportunities = new List<Opportunity>([SELECT Id, Contact__c
            FROM Opportunity WHERE Contact__c IN :contactIds]);

        Set<Id> relatedOpportunityIds = new Set<Id>();
        Map<Id, Id> opportunityToContact = new Map<Id, Id>();
        for (Opportunity anOpp : relatedOpportunities) {
            opportunityToContact.put(anOpp.Id, anOpp.Contact__c);
            relatedOpportunityIds.add(anOpp.Id);
        }

        // Then we begin the recalculation process by first zeroing out all of the three fields 
        // that make up the annual donation amount, and then recalculating each of them.
        for (Contact c : relatedContacts.values()) {
            c.Sum_One_Time_Last_Year_Donations__c = null;
            c.Sum_Annualized_Sustaining_Donations__c = null;
            c.Sum_Inactive_Last_Year_Donations__c = null;
        }

        // ONE TIME DONATIONS (Payments associated with non-recurring Opportunities)
        String oneTimePaymentQuery = 'SELECT Id, Opportunity__c, Opportunity__r.Contact__c, Amount__c' 
                        		+ ' FROM Payment__c' 
                                + ' WHERE Opportunity__r.Is_Monthly__c = false'
                                + ' AND Status__c NOT IN (\'' + PaymentServices.CANCELLED_STATUS + '\''
                                + ' , \'' + PaymentServices.FAILED_STATUS + '\''
                                + ' , \'' + PaymentServices.PENDING_STATUS + '\''
                                + ' , \'' + PaymentServices.DECLINED_STATUS + '\')'
                                + ' AND Post_Date__c = LAST_N_DAYS:' + OpportunityServices.DAYS_TO_QUERY
                                + ' AND Opportunity__c IN :relatedOpportunityIds';
        List<Payment__c> oneTimePayments = Database.query(oneTimePaymentQuery);

        for (Payment__c paym: oneTimePayments) {
            relatedContacts.get(opportunityToContact.get(paym.Opportunity__c)).Sum_One_Time_Last_Year_Donations__c = 
                Utilities.add(relatedContacts.get(opportunityToContact.get(paym.Opportunity__c)).Sum_One_Time_Last_Year_Donations__c, 
                paym.Amount__c); 
        }

        // ACTIVE RECURRING DONATIONS (All active recurring Opportunities annualized to 12 months)
        // TO DO - In MER-730 two new fields will be generated to capture the amount of a one time donation
        // or the recurring payment amount.  The Initial_Payment_Amount__c field below should be changed to the 
        // field where the one time donation value will be stored.
        String activeRecurringOppsQuery = 'SELECT Id, Contact__c, Initial_Payment_Amount__c' 
                        		+ ' FROM Opportunity'
                                + ' WHERE Is_Monthly__c = true AND Membership_Active__c = true'
                                + ' AND Id IN :relatedOpportunityIds';
        List<Opportunity> activeRecurringOpps = Database.query(activeRecurringOppsQuery);
        
        for (Opportunity opp : activeRecurringOpps) {
            if (opp.Initial_Payment_Amount__c != null) {
                relatedContacts.get(opportunityToContact.get(opp.Id)).Sum_Annualized_Sustaining_Donations__c = 
                    Utilities.add(relatedContacts.get(opportunityToContact.get(opp.Id)).Sum_Annualized_Sustaining_Donations__c, 
                    opp.Initial_Payment_Amount__c * 12); 
            }
        }

        // INACTIVE RECURRING DONATIONS (Payments associated with inactive, recurring Oportunities made within the last 12 months)
        String inactiveRecurringPaymentsQuery = 'SELECT Id, Opportunity__c, Opportunity__r.Contact__c, Amount__c' 
                        		+ ' FROM Payment__c' 
                                + ' WHERE Opportunity__r.Is_Monthly__c = true AND Opportunity__r.Membership_Active__c = false'
                                + ' AND Status__c NOT IN (\'' + PaymentServices.CANCELLED_STATUS + '\''
                                + ' , \'' + PaymentServices.FAILED_STATUS + '\''
                                + ' , \'' + PaymentServices.PENDING_STATUS + '\''
                                + ' , \'' + PaymentServices.DECLINED_STATUS + '\')'
                                + ' AND Post_Date__c = LAST_N_DAYS:' + OpportunityServices.DAYS_TO_QUERY
                                + ' AND Opportunity__c IN :relatedOpportunityIds';
        List<Payment__c> inactiveRecurringPayments = Database.query(inactiveRecurringPaymentsQuery);
        
        for (Payment__c paym : inactiveRecurringPayments) {
            relatedContacts.get(opportunityToContact.get(paym.Opportunity__c)).Sum_Inactive_Last_Year_Donations__c = 
                Utilities.add(relatedContacts.get(opportunityToContact.get(paym.Opportunity__c)).Sum_Inactive_Last_Year_Donations__c, 
                paym.Amount__c); 
        }           

        try {
            update relatedContacts.values();
        } catch (DmlException ex) {
            ErrorLog.logError(ex, 'ContactUtilities', 'Error updating Contact values in recalcAnnualDonationValues.');
            ErrorLog.commitErrors();
            return;            
        }

    }    
}