force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_Inactive_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Inactive_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all donations from inactive sustaining donations in the last year</inlineHelpText>
    <label>Sum Inactive Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sum_One_Time_Last_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_One_Time_Last_Year_Donations__c</fullName>
    <inlineHelpText>The sum of all of the one time donations from this Contact within the last year</inlineHelpText>
    <label>Sum One Time Last Year Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Annualized_Donation_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Annualized_Donation_Value__c</fullName>
    <formula>Sum_One_Time_Last_Year_Donations__c +   Sum_Annualized_Sustaining_Donations__c + Sum_Inactive_Last_Year_Donations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The sum total of all donations from this Contact in the last year</inlineHelpText>
    <label>Total Annualized Donation Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ZeroOutAnnualContactFieldsBatchTest.cls
@IsTest
public class ZeroOutAnnualContactFieldsBatchTest {
    
    static testMethod void testZeroOutValues() {
        List<Contact> contacts = TestUtilities.createContacts(5, false);
        for (Integer i = 0; i < contacts.size(); i++) {
            contacts[i].Sum_One_Time_Last_Year_Donations__c = 100 + (i * 25);
            contacts[i].Sum_Annualized_Sustaining_Donations__c = 60 + (i * 5);
            contacts[i].Sum_Inactive_Last_Year_Donations__c = 40 + (i * 12);
        }

        insert contacts;

        Test.startTest();
            Database.executeBatch(new ZeroOutAnnualContactFieldsBatch(), 200);
        Test.stopTest();

        List<Contact> updatedContacts = [SELECT Id, Sum_One_Time_Last_Year_Donations__c, Sum_Annualized_Sustaining_Donations__c,
            Sum_Inactive_Last_Year_Donations__c, Total_Annualized_Donation_Value__c FROM Contact];

        for (Contact c : updatedContacts) {
            System.assertEquals(null, c.Sum_One_Time_Last_Year_Donations__c, 'Value should be null');
            System.assertEquals(null, c.Sum_Annualized_Sustaining_Donations__c, 'Value should be null');
            System.assertEquals(null, c.Sum_Inactive_Last_Year_Donations__c, 'Value should be null');
            System.assertEquals(0.0, c.Total_Annualized_Donation_Value__c, 'Value should be zero');
        }
       
    }

    
}