force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Amount__c</fullName>
    <label>Initial Payment Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CalcOpportunityTotalBatchTest.cls
@IsTest
public class CalcOpportunityTotalBatchTest {
    
    static testMethod void testActiveRecurDonationTotal() {
        
        List<Account> accounts = TestUtilities.createAccounts(1, true);
        List<Contact> contacts = TestUtilities.createContacts(accounts, 1, true);

        List<Opportunity> opps = TestUtilities.createOpportunities(contacts, 3, false);
        for (Opportunity opp : opps ) {
          opp.Is_Monthly__c = true;
          opp.Membership_Active__c = true;
          opp.CloseDate = Date.today().addMonths(-2);
        }
        opps[0].Initial_Payment_Amount__c = 15;
        opps[1].Initial_Payment_Amount__c = 25;
        opps[2].Initial_Payment_Amount__c = 10;
        opps[2].Membership_Active__c = false; // Testing an Opp that isn't active.       
        insert opps;        

        Test.startTest();
            Database.executeBatch(new ZeroOutAnnualContactFieldsBatch(), 200);
        Test.stopTest();

        List<Contact> updatedContacts = [SELECT Id, Sum_Annualized_Sustaining_Donations__c
             FROM Contact];

        for (Contact c : updatedContacts) {
            System.assertEquals(480, c.Sum_Annualized_Sustaining_Donations__c, 'Value should be 480');
        }
        
    }
   
}