force-app/main/default/objects/Contact/fields/Sum_Annualized_Sustaining_Donations__c.field-meta.xml
<CustomField>
    <fullName>Sum_Annualized_Sustaining_Donations__c</fullName>
    <inlineHelpText>The annualized (x 12) sum of all active sustaining donations</inlineHelpText>
    <label>Sum Annualized Sustaining Donations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact responsible for this donation, if applicable</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Amount__c</fullName>
    <label>Initial Payment Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Is_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Monthly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Membership_Active__c.field-meta.xml
<CustomField>
    <fullName>Membership_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this donation currently qualifies donor for membership benefits</inlineHelpText>
    <label>Membership Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CalcOpportunityTotalBatch.cls
global class CalcOpportunityTotalBatch implements Database.Batchable<sObject>, Database.Stateful {
	
    @TestVisible List<ID> failedList = new List<ID>();

    global Database.QueryLocator start(Database.BatchableContext BC) {
      
        // TO DO - In MER-730 two new fields will be generated to capture the amount of a one time donation
        // or the recurring payment amount.  The Initial_Payment_Amount__c field below should be changed to the 
        // field where the amount of the next recurring donation will be stored.
        String query = 'SELECT Id, Contact__c, Initial_Payment_Amount__c' 
                        		+ ' FROM Opportunity'
                                + ' WHERE Is_Monthly__c = true AND Membership_Active__c = true';
                                // Close Date is not relevant.  Only concern is if Opp is recurring and active.
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> scope){
        
        Map<Id, Id> opportunityToContact = new Map<Id, Id>(); 
        for (Opportunity opp : scope) {
            opportunityToContact.put(opp.Id, opp.Contact__c);
        }   
        
        Map<Id, Contact> contactsInBatch = new Map<Id, Contact>([SELECT Id, Sum_Annualized_Sustaining_Donations__c
                FROM Contact WHERE Id IN :OpportunityToContact.values()]);
        for (Opportunity opp : scope) {
            contactsInBatch.get(opportunityToContact.get(opp.Id)).Sum_Annualized_Sustaining_Donations__c = 
                Utilities.add(contactsInBatch.get(opportunityToContact.get(opp.Id)).Sum_Annualized_Sustaining_Donations__c, 
                opp.Initial_Payment_Amount__c * 12);
        }   

        Database.SaveResult[] sr = Database.Update(contactsInBatch.values(),false);

        for(Integer i=0;i<sr.size();i++){
            if (!sr.get(i).isSuccess()){
                // DML operation failed
                contactsInBatch.values().get(i);
                //capturing the failed payments
                failedList.add(contactsInBatch.values().get(i).Id);
            }
        }
    } 

    global void finish(Database.BatchableContext bc) {
        String failedListString;
        if (!failedList.isEmpty()) {
        
            for (Id theId : failedList) {
                failedListString += theId + ', ';
            }

            ErrorLog.logError(null, 'CalcOpportunityTotalBatch', failedListString);
            ErrorLog.commitErrors();
        }
        // Send admin an email upon success??
    }

}