force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Bill Me</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Worldpay_Token__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Token__c</fullName>
    <inlineHelpText>The tokenized credit card number associated with this payment</inlineHelpText>
    <label>Worldpay Token</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentServices.cls
public class PaymentServices {

    public static final String APPROVED_STATUS = 'Approved';
    public static final String PENDING_STATUS = 'Pending';
    public static final String DECLINED_STATUS = 'Declined';
    public static final String FAILED_STATUS = 'Failed';
    public static final String REFUNDED_STATUS = 'Refunded';
    public static final String CANCELLED_STATUS = 'Cancelled';
    
    @TestVisible
    static List<String> fieldsToMap = new List<String>{
        'Opportunity__c', 'Amount__c', 'Card_Type__C', 'Worldpay_Token__c', 'Payment_Method__c'
    };

    public static Payment__c scheduleNext(Payment__c thePayment) {
        Payment__c newPayment = new Payment__c();
        for (String aField : fieldsToMap) {
            newPayment.put(aField, thePayment.get(aField));
        }
        newPayment.Scheduled_Post_Date__c = thePayment.Scheduled_Post_Date__c.addMonths(1);
        newPayment.Status__c = PENDING_STATUS;
        return newPayment;
    }

}