force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Capture_Sale_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Capture_Sale_Transaction__c</fullName>
    <inlineHelpText>Worldpay Id for the credit card transaction</inlineHelpText>
    <label>Capture/Sale Transaction</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Original_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Payment_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If record is a refund, the approved payment that was refunded</inlineHelpText>
    <label>Original Payment Id</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentRefundControllerTest.cls
@isTest
public with sharing class PaymentRefundControllerTest {
    static testMethod void checkPaymentChildRecordNotExistTest() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
            testPayment.Status__c = PaymentServices.APPROVED_STATUS;
            insert testPayment;
        Test.startTest();
            Boolean refundRecordExists = PaymentRefundController.checkPaymentChildRecord(testPayment.Id);
        Test.stopTest();
        System.assert(!refundRecordExists,'We expect the payment child record does not exist.');
    }
    static testMethod void checkPaymentChildRecordExistTest() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
            testPayment.Status__c = PaymentServices.APPROVED_STATUS;
            insert testPayment;
        Payment__c testChildPayment = new Payment__c();
            testChildPayment.Opportunity__c = testOpp.Id;
            testChildPayment.Amount__c = -10.00;
            testChildPayment.Scheduled_Post_Date__c = Date.today();
            testChildPayment.Original_Payment_Id__c = testPayment.Id;
            testChildPayment.Status__c = PaymentServices.REFUNDED_STATUS;
            insert testChildPayment;
        Test.startTest();
            Boolean refundRecordExists = PaymentRefundController.checkPaymentChildRecord(testPayment.Id);
        Test.stopTest();
        System.assert(refundRecordExists,'We expect the payment child record should exist.');
    }
    static testMethod void createRefundPaymentRecordTest() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
        Payment__c childRec = new Payment__c();
            childRec.Status__c =  PaymentServices.REFUNDED_STATUS;
            childRec.Amount__c = -10.00;
            childRec.Opportunity__c = testOpp.Id;
        Test.startTest();
            Payment__c refundRecord = PaymentRefundController.createRefundPaymentRecord(testPayment.Id,childRec);
        Test.stopTest();
        System.assertEquals(testPayment.Id, refundRecord.Original_Payment_Id__c,'We expect the refund record has been created');
        System.assertEquals((-1 * testPayment.Amount__c), refundRecord.Amount__c, 'We expect the refund record amount to be the negative value of the parent payment');
    }
    static testMethod void refundDonationTest() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        List<Contact> testContact = TestUtilities.createContacts(testAccount, 1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, testContact, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
            testPayment.Capture_Sale_Transaction__c = '82922712172354325';
            testPayment.Status__c = PaymentServices.APPROVED_STATUS;
            insert testPayment;
        VantivUtilitiesMock theMock = new VantivUtilitiesMock();
        Test.setMock(HttpCalloutMock.class, theMock);
        Test.startTest();
            Payment__c refundRecord = PaymentRefundController.refundDonation(testPayment.Id);
        Test.stopTest();
        System.assertEquals(testPayment.Id, refundRecord.Original_Payment_Id__c,'We expect the refund record has been created.');
        System.assertEquals((-1 * testPayment.Amount__c), refundRecord.Amount__c, 'We expect the refund record amount to be the negative value of the parent payment');
        System.assertEquals(PaymentServices.REFUNDED_STATUS, refundRecord.Status__c,'We expect the refund record status should be Refunded.');
    }
}