force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Worldpay_Token__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Token__c</fullName>
    <inlineHelpText>The tokenized credit card number associated with this payment</inlineHelpText>
    <label>Worldpay Token</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonationFormPaymentBatch.cls
global class DonationFormPaymentBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    @TestVisible List<ID> failedList = new List<ID>();
	
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Scheduled_Post_Date__c, Status__c, Opportunity__c, Opportunity__r.Id, Amount__c,' 
								+ ' Worldpay_Token__c'
                        		+ ' FROM Payment__c where Status__c=\'Pending\' and Scheduled_Post_Date__c = LAST_N_DAYS:7';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Payment__c> scope){
        List<Payment__c> pmtList = new List<Payment__c>(); 
        
        for (Payment__c payment : scope) {
           //Starting vantiv sale callout
            Payment__c thePayment = VantivUtilities.performSale(payment);
            pmtList.add(thePayment);   
        }
        Database.SaveResult[] sr = Database.Update(pmtList,false);
        
        for(Integer i=0;i<sr.size();i++){
            if (!sr.get(i).isSuccess()){
                // DML operation failed
                pmtList.get(i);
                //capturing the failed payments
                failedList.add(pmtList.get(i).Id);
            }
        }
    }  

    global void finish(Database.BatchableContext bc) {
        if (!failedList.isEmpty()) {
            String failedListString;
        
            for (Id theId : failedList) {
                failedListString += theId + ', ';
            }

            ErrorLog.logError(null, 'DonationFormPaymentBatch', failedListString);
            ErrorLog.commitErrors();
        }
    }

}