force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Capture_Sale_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Capture_Sale_Transaction__c</fullName>
    <inlineHelpText>Worldpay Id for the credit card transaction</inlineHelpText>
    <label>Capture/Sale Transaction</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Original_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Payment_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If record is a refund, the approved payment that was refunded</inlineHelpText>
    <label>Original Payment Id</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Worldpay_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Worldpay_Order_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Worldpay unique identifier</inlineHelpText>
    <label>Worldpay Order Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PaymentRefundController.cls
public class PaymentRefundController {

    @AuraEnabled
    public static Boolean checkPaymentChildRecord(Id originalPaymentId) {
        Boolean hasChildPaymentRec = false;

        try {
            Payment__c parentPayment = [SELECT Name, Status__c, (SELECT Name FROM Payments__r) 
                                        FROM Payment__c 
                                        WHERE Id =: originalPaymentId];
            List<Payment__c> childPaymentRecord = parentPayment.Payments__r;
            if (childPaymentRecord.size() > 0 || parentPayment.Status__c == PaymentServices.REFUNDED_STATUS) {
                hasChildPaymentRec = true;
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return hasChildPaymentRec;
    }

    @AuraEnabled
    public static Payment__c refundDonation(Id originalPaymentID) {
        Payment__c refundPayment = new Payment__c();
        Payment__c refundedPayment;

        try {
            Payment__c theOriginalPayment = [SELECT Id,Amount__c,Opportunity__c,Opportunity__r.Id,
                                                Scheduled_Post_Date__c,Worldpay_Order_Id__c,
                                                Status__c,Capture_Sale_Transaction__c 
                                            FROM Payment__c 
                                            WHERE ID =: originalPaymentId];
            refundPayment = VantivUtilities.performRefund(theOriginalPayment);
           
            if (refundPayment != null) {
                refundPayment.Amount__c = (-1 * theOriginalPayment.Amount__c);
                refundPayment.Opportunity__c = theOriginalPayment.Opportunity__r.Id;
                refundedPayment = createRefundPaymentRecord(originalPaymentId, refundPayment);
            }

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return refundedPayment;
    }

    @TestVisible
    static Payment__c createRefundPaymentRecord(Id originalPaymentId,Payment__c refundPaymentData) {
        if (originalPaymentId != null && refundPaymentData != null) {
            refundPaymentData.Original_Payment_Id__c = originalPaymentId;
            insert refundPaymentData;
        }       
        return refundPaymentData;
    }
}