force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <inlineHelpText>Date a payment was processed by Worldpay (if blank, transaction has not yet occurred)</inlineHelpText>
    <label>Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Post_Date__c</fullName>
    <inlineHelpText>Date a payment is scheduled to be processed by Worldpay</inlineHelpText>
    <label>Scheduled Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentServicesTest.cls
@IsTest
public class PaymentServicesTest {
    
    static testMethod void testScheduleNext() {
        List<Account> testAccount = TestUtilities.createAccounts(1, true);
        Opportunity testOpp = TestUtilities.createOpportunities(testAccount, 1, true)[0];
        Payment__c testPayment = TestUtilities.createPayment(testOpp, false);
        testPayment.Status__c = PaymentServices.APPROVED_STATUS;
        testPayment.Post_Date__c = Date.today();
        testPayment.Scheduled_Post_date__c = Date.today();
        insert testPayment;
        Test.startTest();
            Payment__c newPayment = PaymentServices.scheduleNext(testPayment);
        Test.stopTest();

        System.assertEquals(PaymentServices.PENDING_STATUS, newPayment.Status__c,
            'Expect the new payments status to be pending');
        System.assertEquals(Date.today().addMonths(1), newPayment.Scheduled_Post_Date__c,
            'Expect the new payments scheduled post date to be one month out');
        for (String aField : PaymentServices.fieldsToMap) {
            System.assertEquals(testPayment.get(aField), newPayment.get(aField),
                'Expect each specified field to be mapped from the old payment to the new: ' + aField);
        }
    }

}